### ISSUE TITLE
Am i missing a variable thats not spelled out for Vnet creation 

### ISSUE THREAD

**Issue by frankscalzo** [Azure/terraform-azurerm-lz-vending#100]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**:

#### Describe the bug

I run the program without creating a vnet no issue.

when i try to enable Vnet creation i get up to RG creation and get a link failure its looking for a 000 subscription

see below

azapi_resource.telemetry_root[0]: Creation complete after 13s [id=/subscriptions/25XXXXXa-c9ed-41b4-XXXX-6937afeef16d/providers/Microsoft.Resources/deployments/pid-50a8a460-d517-4b11-b86c-6de447806b67_0.3.0_00000d03]
╷
│ Error: creating/updating "Resource: (ResourceId \"/subscriptions/25XXXXXXa-c9ed-41b4-XXXX-6937afeef16d/resourceGroups/Demo-Epic-Prod-rgp/providers/Microsoft.Network/virtualNetworks/Demo_Epic_Prod_Vnet\" / Api Version \"2021-08-01\")": PUT https://management.azure.com/subscriptions/253XXXXX-c9ed-41b4-XXXX-6937afeef16d/resourceGroups/Demo-Epic-Prod-rgp/providers/Microsoft.Network/virtualNetworks/Demo_Epic_Prod_Vnet
│ --------------------------------------------------------------------------------
│ RESPONSE 403: 403 Forbidden
│ ERROR CODE: LinkedAuthorizationFailed
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "LinkedAuthorizationFailed",
│     "message": "The client has permission to perform action 'Microsoft.Network/ddosProtectionPlans/join/action' on scope '/subscriptions/253XXXX-c9ed-41b4-XXXX-6937afeef16d/resourceGroups/Demo-Epic-Prod-rgp/providers/Microsoft.Network/virtualNetworks/Demo_Epic_Prod_Vnet', however the linked subscription '00000000-0000-0000-0000-000000000000' was not found. "
│   }
│ }
│ --------------------------------------------------------------------------------
│ 
│ 
│   with module.virtualnetwork[0].azapi_resource.vnet,
│   on modules/virtualnetwork/main.tf line 32, in resource "azapi_resource" "vnet":
│   32: resource "azapi_resource" "vnet" {
│ 

I dont find DDos in any of the files other than an example and i dont have it turned on in my current deployment since i will not allow inbound this is all private 

also does this not support subnet creation during vnet creation?

#### Steps to Reproduce

1. step 1
2. step 2
3. you get it...

**Comment by matt-FFFFFF** [comment]
Hi @frankscalzo 

Can you post your module configuration?

As for subnets, this is intentional. There are so many options for a subnet that it is too cumbersome at the moment.

https://docs.microsoft.com/en-us/azure/templates/microsoft.network/virtualnetworks/subnets?pivots=deployment-language-bicep#resource-format

Our thinking is that the application teams can configure subnets when they get the LZ provisioned.

**Comment by frankscalzo** [comment]
@matt-FFFFFF 

im assuming you wanted the variables.virtualnetwork.tf

# Note:
# Variable validation rules are disabled in the parent module and defaults supplied
# to support the case when the user does not want the virtual network to be deployed.

variable "virtual_network_enabled" {
  type        = bool
  description = <<DESCRIPTION
Enables and disables the virtual network submodule.
DESCRIPTION
  default     = true
}

variable "virtual_network_name" {
  type        = string
  description = <<DESCRIPTION
The name of the virtual network.
DESCRIPTION
  default     = "Demo_Epic_Prod_Vnet"
}

variable "virtual_network_address_space" {
  type        = list(string)
  description = <<DESCRIPTION
The address space of the virtual network, supplied as multiple CIDR blocks, e.g. `["10.0.0.0/8","172.16.0.0/12"]`.
DESCRIPTION
  default     = ["172.22.16.0/22"]
}

variable "virtual_network_peering_enabled" {
  type        = bool
  description = <<DESCRIPTION
Whether to enable peering with the supplied hub virtual network.
Enables a hub & spoke networking topology.

If enabled the `hub_network_resource_id` must also be suppled.
DESCRIPTION
  default     = false
}

variable "hub_network_resource_id" {
  type        = string
  description = <<DESCRIPTION
The resource ID of the virtual network in the hub to which the created virtual network will be peered.

E.g. `/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-rg/providers/Microsoft.Network/virtualNetworks/my-vnet`

Leave blank to create the virtual network without peering.
DESCRIPTION
  default     = "/subscriptions/2215c1a7-XXXX-4600-XXXXX-XXXX/resourceGroups/ohit-connectivity-eastus2/providers/Microsoft.Network/virtualNetworks/ohit-hub-eastus2"
}

variable "virtual_network_vwan_connection_enabled" {
  type        = bool
  description = <<DESCRIPTION
Whether to enable connection with supplied vwan hub.
Enables a vwan networking topology.

If enabled the `vwan_hub_resource_id` must also be supplied.
DESCRIPTION
  default     = true
}

variable "vwan_hub_resource_id" {
  type        = string
  description = <<DESCRIPTION
The resource ID of the vwan hub to which the virtual network will be connected.
E.g. `/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-rg/providers/Microsoft.Network/virtualHubs/my-hub`

Leave blank to create a virtual network without a vwan hub connection.
DESCRIPTION
  default     = "/subscriptions/221XXXX-50bb-XXXX-XXXX-88216acfbeb2/resourceGroups/ohit-connectivity/providers/Microsoft.Network/virtualHubs/ohit-hub-eastus2"
}

variable "virtual_network_resource_group_name" {
  type        = string
  description = <<DESCRIPTION
The name of the resource group to create the virtual network in.
DESCRIPTION
  default     = "Demo-Epic-Prod-rgp"
}

variable "virtual_network_location" {
  type        = string
  description = <<DESCRIPTION
The location of the virtual network.

Use this to override the default location defined by `var.location`.
Leave blank to use the default location.
DESCRIPTION
  default     = "eastus"
}

variable "virtual_network_use_remote_gateways" {
  type        = bool
  description = <<DESCRIPTION
Enables the use of remote gateways for the virtual network.

Applies to hub and spoke (vnet peerings).
DESCRIPTION
  default     = true
}

variable "virtual_network_vwan_associated_routetable_resource_id" {
  type        = string
  description = <<DESCRIPTION
The resource ID of the virtual network route table to use for the virtual network.

Leave blank to use the `defaultRouteTable`.

E.g. `/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-rg/providers/Microsoft.Network/virtualHubs/my-vhub/hubRouteTables/defaultRouteTable`
DESCRIPTION
  default     = ""
}

variable "virtual_network_vwan_propagated_routetables_resource_ids" {
  type        = list(string)
  description = <<DESCRIPTION
The list of route table resource ids to advertise routes to.

Leave blank to use the `defaultRouteTable`.
DESCRIPTION
  default     = []
}

variable "virtual_network_vwan_propagated_routetables_labels" {
  type        = list(string)
  description = <<DESCRIPTION
The list of virtual WAN labels to advertise the routes to.

Leave blank to use the `default` label.
DESCRIPTION
  default     = []
}

variable "virtual_network_resource_lock_enabled" {
  type        = bool
  description = <<DESCRIPTION
Enables the deployment of resource locks to the virtual network's resource group.
Currently only `CanNotDelete` locks are supported.
DESCRIPTION
  default     = true
}

**Comment by frankscalzo** [comment]
@matt-FFFFFF let me know if you need anything else i would love to solve this so i can incorporate into my plan

**Comment by matt-FFFFFF** [comment]
Hi @frankscalzo 

It's a public holiday here in the UK today. I'll look at this in the coming week.

**Comment by frankscalzo** [comment]
@matt-FFFFFF no worries totally understand. was not aware you were in the UK.  wishing you well

**Comment by matt-FFFFFF** [comment]
Hi @frankscalzo 

It seems you are using the repo as a root module. Although it may work, it's not really designed to be used this way.

Would you try and reproduce this using your own root module, then calling this as a sub-module?

If you could then post the module declaration in your code I can investigate.

**Comment by frankscalzo** [comment]
@matt-FFFFFF  Sorry I will work on today i was under weather last week still a little foggy bt will see what i can do

**Comment by frankscalzo** [comment]
@matt-FFFFFF 

so when i use them as modules i get through everything but i had to disable telemetry if i keep it i get a location error 

even when the location is set in the variables correctly i think 

module.lz_vending.module.virtualnetwork[0].azapi_resource.vhubconnection["this"]: Creation complete after 2m13s [id=/subscriptions/2215c1a7-50bb-4600-b597-88216acfbeb2/resourceGroups/ohit-connectivity/providers/Microsoft.Network/virtualHubs/ohit-hub-eastus2/hubVirtualNetworkConnections/vhc-be1e8fb5-6fa5-5436-9004-fc82ab87df13]
╷
│ Error: creating/updating "Resource: (ResourceId \"/subscriptions/651fdcaa-6d1b-4316-bf19-b7b17dbbcd69/providers/Microsoft.Resources/deployments/pid-50a8a460-d517-4b11-b86c-6de447806b67_0.3.0_00000503\" / Api Version \"2021-04-01\")": PUT https://management.azure.com/subscriptions/651fdcaa-6d1b-4316-bf19-b7b17dbbcd69/providers/Microsoft.Resources/deployments/pid-50a8a460-d517-4b11-b86c-6de447806b67_0.3.0_00000503
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: InvalidDeployment
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "InvalidDeployment",
│     "message": "The 'location' property must be specified for 'pid-50a8a460-d517-4b11-b86c-6de447806b67_0.3.0_00000503'. Please see https://aka.ms/deploy-to-subscription for usage details."
│   }
│ }
│ --------------------------------------------------------------------------------
│ 
│ 
│   with module.lz_vending.azapi_resource.telemetry_root[0],
│   on .terraform/modules/lz_vending/main.telemetry.tf line 3, in resource "azapi_resource" "telemetry_root":
│    3: resource "azapi_resource" "telemetry_root" {
│ 

i used your demo TF with a few extra since im using Vwan

module "lz_vending" {
  source  = "Azure/lz-vending/azurerm"
  version = ">=1.0.0" # change this to your desired version, https://www.terraform.io/language/expressions/version-constraints

  # subscription variables
  subscription_alias_enabled = true
  subscription_billing_scope = "/providers/Microsoft.Billing/billingAccounts/20769a14-c6b5-5337-6333-6XXXXXXX:e1dc99f8-e55a-4f32-XXXXX-4fXXXXXX11_2019-05-31/billingProfiles/DB4C-2SO2-BG7-PGB/invoiceSections/PA33-IVDZ-PJA-PGB"
  subscription_display_name  = "my-subscription-display-name"
  subscription_alias_name    = "my-subscription-alias"
  subscription_workload      = "Production"

  # management group association variables
  subscription_management_group_association_enabled = true
  subscription_management_group_id                  = "ohit-epic-prod"
  # Telementarty  
  #location          = eastus2
  disable_telemetry = true
  # virtual network variables
  virtual_network_enabled               = true
  virtual_network_address_space         = ["172.22.24.0/22"]
  virtual_network_location              = "eastus2"
  virtual_network_name                  = "ohittestepicprod"
  virtual_network_resource_group_name   = "my-ohitepic-rg"
  virtual_network_resource_lock_enabled = false
  # virtual network peering
  virtual_network_peering_enabled = false
  hub_network_resource_id         = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-hub-network-rg/providers/Microsoft.Network/virtualNetworks/my-hub-network"
  # virtual Wan network peering
  virtual_network_vwan_connection_enabled                = true
  vwan_hub_resource_id                                   = "/subscriptions/221XXXXXX-50bb-4600-b597-88216acfbeb2/resourceGroups/ohit-connectivity/providers/Microsoft.Network/virtualHubs/ohit-hub-eastus2"
  virtual_network_vwan_associated_routetable_resource_id = ""
  # role assignments
  role_assignment_enabled = false
  role_assignments = [
    # using role definition name, created at subscription scope
    {
      principal_id   = "00000000-0000-0000-0000-000000000000"
      definition     = "Contributor"
      relative_scope = ""
    },
    # using a custom role definition
    {
      principal_id   = "11111111-1111-1111-1111-111111111111"
      definition     = "/providers/Microsoft.Management/MyMg/providers/Microsoft.Authorization/roleDefinitions/ffffffff-ffff-ffff-ffff-ffffffffffff"
      relative_scope = ""
    },
    # using relative scope (to the created or supplied subscription)
    {
      principal_id   = "00000000-0000-0000-0000-000000000000"
      definition     = "Owner"
      relative_scope = "/resourceGroups/MyRg"
    },
  ]
}

**Comment by matt-FFFFFF** [comment]
Hi @frankscalzo 

I'm glad you are getting somewhere.

In terms of the telemetry, the `var.location` input is mapped to the ARM deployment so should work if it's correctly mapped to an Azure region.
