### ISSUE TITLE
Feature Request: Add vnet_id as an output

### ISSUE THREAD

**Issue by ChrisTav424** [Azure/terraform-azurerm-lz-vending#101]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

**Is your feature request related to an issue?**
No

We would like to use the vnet_id of any vnets that are generated from this vending module without having to use a data source. 

### Describe the solution you'd like

[outputs.tf](https://github.com/Azure/terraform-azurerm-lz-vending/blob/main/outputs.tf) to include the vnet_id of any vnets it creates. At present it only outputs the subscription_id's. It looks like vnet_id is in the [output.tf](https://github.com/Azure/terraform-azurerm-lz-vending/blob/main/modules/virtualnetwork/outputs.tf) from the virtualnetwork submodule 

### Additional context
This will allow us to use this vending module to create a 'connectivity' subscription and then pass the vnet_id into any other subscriptions for vnet peering them back to the connectivity.

**Comment by matt-FFFFFF** [comment]
Hi @ChrisTav424

Thanks for the request - shouldn't be a problem for the v2 release

**Comment by ASHR4** [comment]
When is the V2 Due? There is no date on the milestone

**Comment by matt-FFFFFF** [comment]
Hi,

Now TF 1.3 is released I'll work on it in October.

It's quite a big change given the network complex object.

I will update the milestone
