### ISSUE TITLE
Feature Request - Ability to re-establish lz-vending hub peering in cases where hub(s) has been redeployed

### ISSUE THREAD

**Issue by cbezenco** [Azure/terraform-azurerm-lz-vending#128]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

**Is your feature request related to an issue?**  Not really an issue but implementing this feature request would allow to reduce costs in dev/test environment and also improve reliability/stability of production environment where ESLZ hub is redeployed. 
 
I am using ALZ in my lab and to keep cost down, I am redeploying ESLZ on a regular basis (week-end or even daily). 
After implementing lz-vending, I initially followed standard workflow (aka tf destroyed my workloads, tf destroyed lz-vending deployment and updated eslz with hubs disabled. As it takes significant time, I tried to see what happened if I only redeployed ESLZ with hubs disabled without touching workload and lz-vending. 

In my test, adding back the ESLZ hubs went smoothly. Vending subnet peering status moved as Disconnected as expected. 
In order to reconnect the vending vnets with hub, I re-applied my tz-vending deployment and 2 issues: 

1. Error triggered because there is no azurerm_management_group_subscription_association
│ Error: could not read properties for Management Group "dev-landing-zones" with module.lz_vending["landing_zone_1.yaml"].module.subscription[0].azurerm_management_group_subscription_association.this[0], on .terraform\modules\lz_vending\modules\subscription\main.tf line 20, in resource azurerm_management_group_subscription_association" "this":
│   20: resource "azurerm_management_group_subscription_association" "this" {

I am not sure why but removing ESLZ hub seemed to have moved back vending subscriptions under my "New Subscriptions" MG. Moving back manually one of the subscriptions ensured there was at least one  "azurerm_management_group_subscription_association" and redeplyment of all lz-vending sub under the proper MG went smoothly but then 2nd error popped-up:

2. Error when trying to re-establish peer with newly created hub
│ Error: creating/updating "Resource: (ResourceId \"/subscriptions/e4f86ded-632e-46f0-9d88-56cf56ee72c0/resourceGroups/dev-connectivity-northeurope/providers/Microsoft.Network/virtualNetworks/dev-hub-northeurope/virtualNetworkPeerings/peer-629dbe4b-43c7-5b24-942f-18233610489c\" / Api Version \"2021-08-01\")": PUT https://management.azure.com/subscriptions/e4f86ded-632e-46f0-9d88-56cf56ee72c0/resourceGroups/dev-connectivity-northeurope/providers/Microsoft.Network/virtualNetworks/dev-hub-northeurope/virtualNetworkPeerings/peer-629dbe4b-43c7-5b24-942f-18233610489c
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: RemotePeeringIsDisconnected
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "RemotePeeringIsDisconnected",
│     "message": "Cannot create or update peering /subscriptions/e4f86ded-632e-46f0-9d88-56cf56ee72c0/resourceGroups/dev-connectivity-northeurope/providers/Microsoft.Network/virtualNetworks/dev-hub-northeurope/virtualNetworkPeerings/peer-629dbe4b-43c7-5b24-942f-18233610489c because remote peering /subscriptions/0f11ed9d-9abc-480a-8ab0-4220af1c954b/resourceGroups/rg-vnets/providers/Microsoft.Network/virtualNetworks/vnet-dev-lz02-01/virtualNetworkPeerings/peer-a95edc20-3b69-5411-bf23-518807b277d6 referencing parent virtual network /subscriptions/e4f86ded-632e-46f0-9d88-56cf56ee72c0/resourceGroups/dev-connectivity-northeurope/providers/Microsoft.Network/virtualNetworks/dev-hub-northeurope is in Disconnected state. Update or re-create the remote peering to get it back to Initiated state. Peering gets Disconnected when remote vnet or remote peering is deleted and re-created.",
│     "details": []
│   }
│ } 

I did not manage to find a quick workaround for this one. If there is an easy fix then I believe there is feature request could help reduce costs/time of our dev workflow and also potentially add some level of reliability by enabling lz-vending to work in case of hub redeployment. 

### Describe the solution you'd like

Ability to re-establish peering with newly created hub.

**Comment by matt-FFFFFF** [comment]
Hi @cbezenco 

Thanks for raising this. The second issue that you describe is caused by the hub network being deleted, along with one half of the peering.

In this case I would recommend disabling hub peering before you delete the hub network.  This will ensure that the state is consistent.
