### ISSUE TITLE
feat: add internet security for vhub connections

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-azurerm-lz-vending#137]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

https://learn.microsoft.com/en-us/azure/templates/microsoft.network/virtualhubs/hubvirtualnetworkconnections?pivots=deployment-language-bicep

Add `enableInternetSecurity` bool

[AB#25716](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/25716)

**Is your feature request related to an issue?**

**Comment by b0bu** [comment]
I had a look at this today and as far as I can tell adding `enableInternetSecurity` is the easy bit. I have a need for both secure internet and secure private traffic for each vhub fw I deploy. Enabling internet security doesn't do anything unless the 0/0 route in the in the vhub defaultRouteTable is pointing to the firewall. I propose adding something like the following to the vnet configuration 

```
    security_configuration = object({
        secure_internet_traffic = optional(bool, false)
        secure_private_traffic = optional(bool, false)
        next_hop = string
    })
```

And having the defaultRouteTable updated based on the presence of security_configuration. I forked this today and have it working https://github.com/b0bu/terraform-azurerm-lz-vending/blob/c41df2f0ca84d660777971e57c87da8dd8de03d2/modules/virtualnetwork/main.tf#L143. Not sure how you feel about the approach so haven't opened a PR yet. There may be another part of this code base that I'm unfamiliar with that allows you to manipulate the route table.
