### ISSUE TITLE
feat: updated documentation on usage with ALZ

### ISSUE THREAD

**Issue by geertklop** [Azure/terraform-azurerm-lz-vending#142]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

The documentation on integration with the ALZ module describes the following when using the vending module:

```
# management group association variables
subscription_management_group_association_enabled = true
subscription_management_group_id                                 = "mymg"
```

However, the management_group_id called `"mymg"` isn't referenced in the ALZ block above. This might be confusing and lead to potential bugs / undocumented dependencies. 

For example, if I create `"mymg"` with the `custom_landing_zones` property of ALZ and I destroy ALZ resources and then my want to update subscription resources, then I get the the error message:

`"'/providers/Microsoft.Management/managementGroups/mymg' not found"`

### Describe the solution you'd like

* Updated Example where `"mymg"` is created as a custom landing zone 
* Dependency graph between ALZ and the vending module

**Comment by matt-FFFFFF** [comment]
Hi @geertklop 

Thanks for this feedback. I will update the example to be more clear!
