### ISSUE TITLE
feat: Creating and Managing NSG, UDR 

### ISSUE THREAD

**Issue by chanakanissanka** [Azure/terraform-azurerm-lz-vending#148]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

**Is your feature request related to an issue?**

Partially

We started using this today and deployed successfully. Few things to check before we go deep.
Creating and managing UDR and NSG, does that something offer here or do we need to take care of that ? Apologies if I have missed an obvious 

Nice and easy way to create and manage NSG/UDR for spoke

**Comment by matt-FFFFFF** [comment]
Hi @chanakanissanka 

Thanks for raising this. We have had a request on our Bicep sister project to manage route tables using the subscription vending module.

I would be interested to see how you think this could be implemented. We do not deploy subnets with this module, a conscious decision. Given that nsg and udrs are assigned to subnets then we couldn't do this assignment.

We could provision some UDR and NSG resources in the new subscription though.

What are your thoughts here?

**Comment by matt-FFFFFF** [comment]
@chanakanissanka 

In the mean time you can use the module outputs and the AzAPI provider to deploy any resource not included in the module to the new subscription.

I will provide an example of how to do this in the wiki shortly.

**Comment by chanakanissanka** [comment]
@matt-FFFFFF , Thanks for your faster turnaround on this. 
Perfectly make sense the conscious decision as it's a module eod. 
I have done similar thing before, for a customer where I have to write whole tf-code due to a special requirement. 
More than happy to be wrong or get feed back on this, 
looking at this module, how about we took an approach of providing subnets and their name, Initially we ask an optional parameter, to provide subnet ranges/names ( of course with in VNET address space ) 
subnet_names             = ["Bastian-sub", "spare-1", "spare-2"]
subnet_prefixes          = ["10.144.0.32/27", "10.144.0.64/27", "10.144.0.96/27"]
Then we add condition if "subnet_names" and "sunbet_prefixes" not null, go ahead and create nsg/udr with default values. ( just some default values that can be changed later with a PR )

**Comment by matt-FFFFFF** [comment]
Hi @chanakanissanka 

We do not have any plans to add subnets to the lz-vending modules due to the sheer number of parameters available: https://learn.microsoft.com/azure/templates/microsoft.network/virtualnetworks/subnets?pivots=deployment-language-terraform#resource-format-2

We believe this would make the module too complex, and suggest that subnets are deployed by the owners/users of the newly created subscription.

In terms of this module deploying route tables, we have this on our backlog. The process for creating subnets can then link to this route table at creation time.

However if you want to create route tables and NSGs today, you can do this as depicted in teh diagram below.

```mermaid
sequenceDiagram
    participant root module
    participant lz-vending
    root module->>lz-vending: Input parameters
    lz-vending->>lz-vending: Provisions resources
    lz-vending->>root module: Output subscription id
    root module->>root module: Provisions more resources<br />using subscription id
```

**Comment by chanakanissanka** [comment]
@matt-FFFFFF (Like this last name :) ) 
It perfectly makes sense the point. I 100% agree, and even if it's doable, it will complicate things left and right. As owners, we can take care of it by ourselves: nice chatting and all the best for future discoveries.
