### ISSUE TITLE
feat:Report on Subscription Creator role assignment in Azure Tenant

### ISSUE THREAD

**Issue by mo-SteveGrant** [Azure/terraform-azurerm-lz-vending#152]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

**Is your feature request related to an issue?** No

I need to be able to report on where the subscription creator role(s) have been assigned to SPN(s) within my Azure tenant.

### Describe the solution you'd like

When subscription creator is assigned to an SPN this is done via an API call rather than assigning a RBAC role in the Azure Portal. This makes it difficult to report on where subscription creator has been assigned. Business teams such as Security or InfoSec require a simple to run report that will detail which Azure EA Account has subscription creator assigned and to which SPN(s). 

This report ought be in the Azure Portal alongside the newly ported EA functionality, making this will be consistent with the user experience that already exists.

**Comment by matt-FFFFFF** [comment]
Hi @mo-SteveGrant,

Thanks for raising the issue. There is nothing we can do in this module to provide this reporting capability, however I think your feedback is valid.

I will try to put this on the commerce team's backlog. In the mean time we can explore options on how to produce this data. It seems like an iterative process to:

1. get all billing accounts,
2. list all billing role assignments with subscription creator role
3. export object ids

Thoughts?

**Comment by mo-SteveGrant** [comment]
Hi Matt,

Yes, that sounds a useful approach. Thinking about the potential users of a report like this, having it in the Azure Portal would be beneficial as it needs to be as clear and simple to use as listing RBAC roles for subscriptions and other Azure objects. A final step of resolving the object IDs to object name would also clarify who has this role assigned.

Thanks,

Steve Grant
Solution Architect - Azure, Platform Technology
Met Office | FitzRoy Road | Exeter | Devon | EX1 3PB

**Comment by matt-FFFFFF** [comment]
Tracked internally as AB#26361

**Comment by matt-FFFFFF** [comment]
Thanks @mo-SteveGrant 

I am going to close this issue as it doesn't pertain to this module, however we now have this on our backlog. Reach out if you need an update.
