### ISSUE TITLE
bug: Creation of AAD Groups and assignment of custom role

### ISSUE THREAD

**Issue by cssja** [Azure/terraform-azurerm-lz-vending#153]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

2.1.1

Please paste the output of `terraform version` command from within the initialized directory:

```text
<output of terraform version>
```

Please enter the module version that you are using:

```text
<module version>
```

### Description

I would like to create AAD groups for a new subscription in the same run as creation of the new subscription, and assign appropriate roles to these groups on the newly created subscription. One of these roles is a custom role whose definition is on the _intermediate root_ management group.
 For this I create an additional groups.tf, in which the AAD groups are created and then the roles on the subscription are assigned. 

```
//AAD Group creation
resource "azuread_group" "contributor_no_network" {
  display_name     = "AZ_RBAC_subscriptionContributorNoNetwork"
  security_enabled = true
}

//Management group association
resource "azurerm_management_group_subscription_association" "mg_association" {
  management_group_id = "/providers/Microsoft.Management/managementGroups/${var.management_group_id}"
  subscription_id     = module.lz-vending.subscription_resource_id
}

//Role assignment
resource "azurerm_role_assignment" "contributor_no_network" {
  depends_on = [ azurerm_management_group_subscription_association.mg_association]
  scope              = module.lz-vending.subscription_resource_id
  role_definition_id = var.roledefinition_customRole_SubscriptionContributorNoNetwork_id
  principal_id       = azuread_group.contributor_no_network[0].id
}

```

My problem is that the subscription is created by default under the _tenant root_ management group, on which the custom role is not defined. I perform in the same code an association of the subscription under a management group that contains the definition. 

However, Terraform still does not find the definition and returns the follwing error:

```
│ Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="RoleAssignmentScopeNotAssignableToRoleDefinition" Message="The role [DEV] Subscription-Contributor-NoNetwork is not available for assignment at the requested scope."
││   with azurerm_role_assignment.contributor_no_network[0],
│   on groups.tf line 49, in resource "azurerm_role_assignment" "contributor_no_network":│   49: resource "azurerm_role_assignment" "contributor_no_network" {
│
```

 Only when I run the same code a second time, the assignment of the Custom Role works.

I tried 
- doing the management group association via the lz-vending module, but that does not work either. Doing it in the groups.tf gives me at least the opportunity to work with "depends_on".
- adding a timer_delay of 60 seconds betweend management group association and role assignment. 

Does creating AAD groups in the same run even match the idea of the lz-vending module? Or should I do this in a separate code? Thanks for any answers and suggestions!

#### Steps to Reproduce

1. step 1
2. step 2
3. you get it...

**Comment by matt-FFFFFF** [comment]
Hi @cssja,

You could try setting the default management group in the hierarchy to one that does have the custom role definition in-scope. I have written a [Terraform module](https://registry.terraform.io/modules/matt-FFFFFF/mg-hierarchysettings/azapi/latest) to do this but the resource definition is here:

https://learn.microsoft.com/azure/templates/microsoft.management/managementgroups?pivots=deployment-language-terraform

Let me know if that solves your issue

**Comment by matt-FFFFFF** [comment]
related to #155

**Comment by cssja** [comment]
Hi @matt-FFFFFF,
thank you for the quick response!

It would be a possible workaround that I have already considered, but its not entirely satisfactory. We work with a DevTest architecture like in [this article](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/testing-approach). In this scenario there will also be two role definitions of the custom role: _customRole_Prod_ on the management group "Contoso" and _customRole_Dev_ on "Contoso-Canary". So if I now set the default management group to Sandbox-Canary, for example, and then drag the Subscription from there, under a management group in Prod, I would get the same problem.

**Comment by matt-FFFFFF** [comment]
Hi @cssja 

Thanks for getting back to me. I understand your issue and how the RBAC role definitions seemingly aren't immediately consistent when the subscription is moved into the mg.

Have you tried the following:

1. Increasing the time_wait between the mg association and the role assignment? I would be interested to understand how long this takes.
2. Checking in the portal once the subscription has been moved to see if you can make the assignment manually?

I think this is probably a caching issue, and refreshing the access token may fix it (hence me asking you to check in the portal.

I believe this is related to Azure/terraform-azurerm-caf-enterprise-scale#536, though this affects AzureRM - and is subsequently tracked upstream by Hashicorp hashicorp/go-azure/helpers#141

Thanks

**Comment by matt-FFFFFF** [comment]
Internal AB#26425

**Comment by cssja** [comment]
Hi @matt-FFFFFF , 
i increased the _time_sleep_ to _4 minutes_ and it seems to work now within one run. That solution is fine for me. Thanks a lot for your help!

For anyone who is facing the same problem, this is the code that works for me:
```
resource "azurerm_management_group_subscription_association" "mg_association" {
  management_group_id = "/providers/Microsoft.Management/managementGroups/${var.management_group_id}"
  subscription_id     = module.lz-vending.subscription_resource_id
}

resource "time_sleep" "wait_240_seconds" {
  depends_on      = [azurerm_management_group_subscription_association.mg_association]
  create_duration = "240s"
}

# Role assignments
resource "azurerm_role_assignment" "contributor_no_network" {
  depends_on         = [time_sleep.wait_240_seconds]
  scope              = module.lz-vending.subscription_resource_id
  role_definition_id = var.roledefinition_customRole_SubscriptionContributorNoNetwork_id
  principal_id       = azuread_group.contributor_no_network[0].id
}
```

**Comment by matt-FFFFFF** [comment]
Thanks @cssja this is good to know and I'll close this issue now.
