### ISSUE TITLE
bug: Error creating Subscription w/ Role Assignment on a new Service Principal

### ISSUE THREAD

**Issue by KashifSaadat** [Azure/terraform-azurerm-lz-vending#157]
### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
Terraform v1.3.7
```

Please enter the module version that you are using:

```text
v2.1.1
```

### Description

I have a reusable module where I am creating a Service Principal and Subscription together. The RBAC ID of the Service Principal is passed in the `role_assignments` variable for the LZ vending module. When I attempt to run this, I get an error as follows:

```
on .terraform/modules/lz.app.subscription/main.roleassignment.tf line 10, in module "roleassignment":
│   10:   for_each                     = local.role_assignments_map
│     ├────────────────
│     │ local.role_assignments_map will be known only after apply
```

It seems this is caused because the local var is generated with a unique id based off the contents of each map, but that isn't known until the Service Principal has been created. A workaround would be to `-target` the SP creation first and then the Subscription, but as this is wrapped in a module and called many times it becomes a bit of a pain to manage.

#### Steps to Reproduce

1. Create a Service Principal and Subscription, similar to below:
```hcl
data "azuread_client_config" "current" {}

resource "azuread_application" "app" {
  display_name = "app"
  owners       = [data.azuread_client_config.current.object_id]
}

resource "azuread_service_principal" "sp" {
  application_id               = var.app_id
  app_role_assignment_required = true
  owners                       = [data.azuread_client_config.current.object_id]
}

module "lz_vending" {
  source = "Azure/lz-vending/azurerm"
  version = "v2.1.1"
  location = var.primary_location
  subscription_alias_enabled = true
  subscription_billing_scope = var.billing_scope
  subscription_display_name  = var.name
  subscription_alias_name    = var.name
  subscription_workload      = "Production"

  subscription_management_group_association_enabled = true
  subscription_management_group_id                  = var.mg_id
  subscription_tags                                 = var.tags
  virtual_network_enabled                           = false
  role_assignment_enabled                           = true
  role_assignments = [
    {
      principal_id   = azuread_service_principal.sp.rbac_id
      definition     = "Owner"
      relative_scope = ""
    }
  ]
}
```
2. Run a `terraform plan`

**Comment by matt-FFFFFF** [comment]
Hi @KashifSaadat 

Good catch. We generate the map key guid for the role assignment based off the principal id, the definition id and and the scope.

Given you are creating the principal in the same plan this explains this error.

I'll look into fixing this with a patch release.

**Comment by KashifSaadat** [comment]
Hey @matt-FFFFFF, many thanks for the quick fix! I suspected there probably would be a breaking change due to the way the local was being generated, couldn't see any way around it.
