### ISSUE TITLE
feat: Will this module support Microsoft Customer Agreement

### ISSUE THREAD

**Issue by AndersRunningen** [Azure/terraform-azurerm-lz-vending#159]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

**Is your feature request related to an issue?**

This is more a question, but there was no template for that. Later this year (the 31st of May for my organization) many organizations will have to migrate from current `Azure EA agreements` to `Microsoft Customer Agreement`. In that regard, will this module continue working? 

From the brief overview of the [azapi provider](https://registry.terraform.io/providers/azure/azapi/latest/docs) I don't see any immediate problems. But the maintainers here might have a better understanding of how this all is configured together and would be able to confirm if this will be an issue or not? 

### Describe the solution you'd like

Would like to confirm that the module will work with `Microsoft Customer Agreement`.

**Comment by jtracey93** [comment]
Hi @AndersRunningen,

The module does indeed support MCAs already. 

You just need to provide the correct billing scope ID to the `subscription_billing_scope` input variable. As per: https://github.com/Azure/terraform-azurerm-lz-vending#input_subscription_billing_scope

Hope this helps

Thanks

Jack

**Comment by AndersRunningen** [comment]
Thank you so much @jtracey93 🙌 Much appreciated 🚀

**Comment by ekrof** [comment]
@jtracey93 what about "Azure Plan" offer ID: 0017G? Will it work with that?

**Comment by jtracey93** [comment]
Yes it will as long as it comes from an MPA/MCA 👍
