### ISSUE TITLE
feat: Register Azure Resource Providers

### ISSUE THREAD

**Issue by stefanstranger** [Azure/terraform-azurerm-lz-vending#210]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

As part of the deployment of Azure Subscriptions I would like to register Azure Resource Providers. 

**Is your feature request related to an issue?**

I would like to have a configuration file containing a list of Azure Resource Providers that will registered for each newly Vending Machine Landing Zone being deployed.

### Describe the solution you'd like

I would like to have a configuration file containing a list of Azure Resource Providers that will registered for each newly Vending Machine Landing Zone being deployed.

Using AzAPI Terraform Provider.

**Comment by jtracey93** [comment]
This should be possible via the `azapi_resource_action` resource with a `POST` right @matt-FFFFFF as a child resource of a subscription to the providers API (https://learn.microsoft.com/en-us/rest/api/resources/providers/register)?

**Comment by matt-FFFFFF** [comment]
/cc @jaredfholgate 

I think we will add this one as it came up today also!

**Comment by jtracey93** [comment]
Just a shame we cannot do easily in Bicep :( (Deployment Scripts to the rescue)

**Comment by matt-FFFFFF** [comment]
This is possible with azapi:

```terraform
resource "azapi_resource_action" "test" {
  type        = "Microsoft.Resources/subscriptions@2021-04-01"
  resource_id = "/subscriptions/${data.azurerm_client_config.current.subscription_id}"
  action      = "/providers/Microsoft.Network/register"
  method      = "POST"
}
```

ref: https://github.com/Azure/terraform-provider-azapi/issues/299#issuecomment-1583842415
