### ISSUE TITLE
feat: Add option to manage the Network Watcher Resource Group

### ISSUE THREAD

**Issue by jaredfholgate** [Azure/terraform-azurerm-lz-vending#211]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

# Description

When destroying a subscription the module runs a provisioner to delete the `NetworkWatcherRG`. This provisioner has a dependency on the Azure CLI and that the resource group exists. It currently 'fails gracefully', but think there may be a better approach to handle this.

### Is your feature request related to an issue?

No

## Describe the solution you'd like

A parameter and associated AzApi resource to add and manage the `NetworkWatcherRG` resource group as part of the lifecycle. This would prevent it's automatic creation when a VNET is added and allow it's destruction prior to the subscription being deleted.

It would also negate the need for this provisioner: https://github.com/Azure/terraform-azurerm-lz-vending/blob/613e9e71ff7b242417b7be3c8861afd5f96da6b2/modules/subscription/main.tf#L11

**Comment by matt-FFFFFF** [comment]
Yep, good idea - will implement
