### ISSUE TITLE
bug: Error creating subscription with existing management group

### ISSUE THREAD

**Issue by jmosswcg** [Azure/terraform-azurerm-lz-vending#217]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
terraform v1.5.1
```

Please enter the module version that you are using:

```text
v3.2.0
```

### Description

I'm trying to use the module to only create subscriptions. I have an existing management group. The SPN I'm using has `owner` permissions to the management group id. Here is my code:

```terraform
module "lzvending" {
  source = "/path/to/code/github/terraform-azurerm-lz-vending"

  location = "uswest2"

  subscription_alias_enabled                        = true
  subscription_alias_name                           = test
  subscription_billing_scope                        = "/providers/Microsoft.Billing/billingAccounts/xxxx/enrollmentAccounts/yyyyy"
  subscription_display_name                         = test
  subscription_management_group_association_enabled = true
  subscription_management_group_id                  = production
  subscription_workload                             = "Production"
}
```

Output of `terraform apply`

```
module.lzvending.module.subscription[0].azurerm_subscription.this[0]: Creating...
╷
│ Error: creating new Subscription (Alias "test"): subscriptions.SubscriptionsClient#AliasCreate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Specified method is not supported."
│ 
│   with module.lzvending.module.subscription[0].azurerm_subscription.this[0],
│   on /path/to/code/github/terraform-azurerm-lz-vending/modules/subscription/main.tf line 2, in resource "azurerm_subscription" "this":
│    2: resource "azurerm_subscription" "this" {
│ 
╵
```

#### Steps to Reproduce

1. clone this repo
2. authenticate as the `spn` that has `owner` permissions
3. terraform init, plan, and apply

#### Screenshots

![Screenshot 2023-06-22 at 2 48 13 PM](https://github.com/Azure/terraform-azurerm-lz-vending/assets/137441155/b1c7e9f3-dd9e-48c7-a984-49aa22563594)

**Comment by matt-FFFFFF** [comment]
Hi, we test this scenario here:

https://github.com/Azure/terraform-azurerm-lz-vending/blob/main/modules/subscription/testdata/TestDeploySubscriptionAliasManagementGroupValid/main.tf

It works in the test framework so we will need to understand what's different.

In your example, you seem to have string values presented without the double quotes. Is this how you've done it in the real code?

**Comment by matt-FFFFFF** [comment]
I think I've spotted the problem.

The management group id is the last segment of the resource id, not the whole thing.

If you are using the AzureRM data source then select the .name property instead of .id.

**Comment by matt-FFFFFF** [comment]
As we tried to explain here but clearly didn't do a good enough job 😄 

https://github.com/Azure/terraform-azurerm-lz-vending#input_subscription_management_group_id

**Comment by jmosswcg** [comment]
> I think I've spotted the problem.
> 
> The management group id is the last segment of the resource id, not the whole thing.
> 
> If you are using the AzureRM data source then select the .name property instead of .id.

```
data "azurerm_management_group" "this" {
  display_name = "production"
}

module "lzvending" {
  source = "/path/to/code/github/terraform-azurerm-lz-vending/modules/subscription"

  subscription_alias_enabled                        = true
  subscription_alias_name                           = "test"
  subscription_billing_scope                        = "/providers/Microsoft.Billing/billingAccounts/xxxx/enrollmentAccounts/yyyyy"
  subscription_display_name                         = "test"
  subscription_management_group_association_enabled = true
  subscription_management_group_id                  = data.azurerm_management_group.this.name
  subscription_workload                             = "Production"
}
```

Unfortunately, it doesn't seem to make a difference. I also added quotes around the strings with no change in behavior.

**Comment by matt-FFFFFF** [comment]
Can I clarify, are you specifying the correct billing scope?

I presume you are replacing the xxxxxx and yyyyyy with the actual values from your Enterprise Agreement?

**Comment by matt-FFFFFF** [comment]
Also I noticed that you are not calling the submodule directly, was this intentional?

Normally we recommend calling the parent module.

**Comment by jmosswcg** [comment]
I think I found the issue! (or at least now I'm able to create the subscriptions). I had to setup a data source for the MCA scope. Once I did this, it ended up working. I also specified the parent module (which required a subscription). Code here:

```
data "azurerm_billing_mca_account_scope" "this" {
  billing_account_name = "xxx"
  billing_profile_name = "yyy"
  invoice_section_name = "zzz"
}

data "azurerm_management_group" "this" {
  display_name = "production"
}

module "lzvending" {
  source = "/path/to/code/github/terraform-azurerm-lz-vending"

  location = "westus2"

  subscription_alias_enabled                        = true
  subscription_alias_name                           = "test"
  subscription_billing_scope                        = data.azurerm_billing_mca_account_scope.this.id
  subscription_display_name                         = "test"
  subscription_management_group_association_enabled = true
  subscription_management_group_id                  = data.azurerm_management_group.this.name
  subscription_workload                             = "Production"
}
```

Thank you for your help @matt-FFFFFF

**Comment by matt-FFFFFF** [comment]
Glad you sorted it!
