### ISSUE TITLE
feat: configure propagate default route option when peering vnet with vwan 

### ISSUE THREAD

**Issue by mo-CarlDavey** [Azure/terraform-azurerm-lz-vending#244]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

When you have the vwan_connection_enabled to peer the virtual network with virtual wan, you might want to set the propagate default route option to disabled so that the virtual network address space does not get propagated.

This has been seen when an Express Route connection is made and the route is being propagated into the circuit. Having the option to enable or disable the usual setting for the peering would be useful here.

Can be set by other methods using the internet_security_enabled property.

This needs to be done as part of the lz-vending module with the proper configuration at the time of processing the module. A subsequent and external task or script can update the connection but the peer will already be in place first and will be too late.

Maybe this could be added?

vwan_internet_security_enabled = true|false

To effect the vnet connection setting:

Propagate Default Route = Enabled|Disabled
_Allows Virtual Hub to propagate a learnt default route to this connection. This flag enables default route propagation to a connection only if the default route is already learned by the Virtual WAN hub as a result of deploying a firewall in the hub or if another connected site has forced tunneling enabled. The default route does not originate in the Virtual WAN hub._

**Comment by jtracey93** [comment]
Hey @mo-CarlDavey,

Thanks for the issue. This property/feature is already part of this module as can be seen here: https://github.com/Azure/terraform-azurerm-lz-vending/blob/main/modules/virtualnetwork/main.tf#L166

This is set by the following input variable: `virtual_networks.<vnetKey>.vwan_security_configuration.secure_internet_traffic`

> See https://github.com/Azure/terraform-azurerm-lz-vending#virtual-wan-values

```terraform
... # Other module code removed for ease of reading
# virtual network variables
  virtual_network_enabled = true
  virtual_networks = {
    vnet1 = {
      name                    = "spoke"
      address_space           = ["192.168.1.0/24"]
      resource_group_name     = "rg-networking"
      vwan_connection_enabled = true
      vwan_hub_resource_id    = azurerm_virtual_hub.example.id
      vwan_security_configuration = {
        secure_internet_traffic = true
      }
    }
  }
```

Setting `secure_internet_traffic` to `true` on your vNet declaration should set this property for you as desired.

Let us know if you have any issues

Thanks

Jack

**Comment by mo-CarlDavey** [comment]
This is a different setting. We already have this set to true. This is the setting we need to change:
![image](https://github.com/Azure/terraform-azurerm-lz-vending/assets/118186680/1e6da65b-f852-45bb-b0dc-5bf34402159d)

**Comment by mo-CarlDavey** [comment]
using the resource "azurerm_virtual_hub_connection" you can specify internet_security_enabled = false to disable the propagate default route.

![image](https://github.com/Azure/terraform-azurerm-lz-vending/assets/118186680/e79b04a2-d832-4cd4-81c8-decd8f114599)

**Comment by jtracey93** [comment]
The variable i mentioned above is this same property, we just use AzApi as a provider. so setting `secure_internet_traffic` to `false` wqill stop the default route propagating to the connection

**Comment by mo-CarlDavey** [comment]
Excellent thank you. I have just deployed a vend and is working as expected. Thank you for your quick responses.

**Comment by mo-CarlDavey** [comment]
![image](https://github.com/Azure/terraform-azurerm-lz-vending/assets/118186680/62b15a93-0652-491f-aa5d-840c439942c7)
![image](https://github.com/Azure/terraform-azurerm-lz-vending/assets/118186680/eeb12d29-c048-4916-8e70-fd24ab42b3f3)

using:

![image](https://github.com/Azure/terraform-azurerm-lz-vending/assets/118186680/b9736e09-eba8-4909-85b2-f00e46ab56c1)
