### ISSUE TITLE
bug:  RESPONSE 400: 400 Bad Request │ ERROR CODE: RemoteVnetHasNoGateways

### ISSUE THREAD

**Issue by Raphael-kainos** [Azure/terraform-azurerm-lz-vending#247]
Hi guys Im currently trying to deploy the LZ-vending module but getting the error seen below in the screenshot even though we have not deploying any Vnet gateways, can you kindly advise. 

Versions

Azurerm = 3.60.0
Azure/LZ-Vending = 3.4.1
Terraform Version = 1.5.0 

 
 
<img width="911" alt="Screenshot 2023-09-01 at 13 13 29" src="https://github.com/Azure/terraform-azurerm-lz-vending/assets/143803576/14f27cab-42b0-4cd0-827a-14e15137176d">

<img width="1215" alt="Screenshot 2023-09-01 at 13 14 57" src="https://github.com/Azure/terraform-azurerm-lz-vending/assets/143803576/bccb8b41-98be-47d6-b2a8-4280b01c13bb">

**Comment by jtracey93** [comment]
Hey @Raphael-kainos,

Please set the variable property of `hub_peering_use_remote_gateways` in the vnet1 block to `false` and this will create the peering without the use remote gateways flag, which is enabled by default.

https://github.com/Azure/terraform-azurerm-lz-vending#hub-network-peering-values

Thanks
