### ISSUE TITLE
feat: A possible way to deploy key vault, route tables etc and accompanying resources to different respective subscriptions in Lz vending loop 

### ISSUE THREAD

**Issue by Raphael-kainos** [Azure/terraform-azurerm-lz-vending#248]
feat: A possible way to deploy key vault, route tables etc and accompanying resources to different respective subscriptions in Lz vending loop 

I've incorporated the LZ Vending module into a for_each loop to enhance its usability. However, since the module autonomously manages subscription deployments, I'm seeking guidance on how to simultaneously deploy additional resources, such as key vaults, route tables, and network security groups (NSGs), alongside each landing zone associated with different subscription.
I would greatly appreciate any suggestions in this regard.

<img width="491" alt="Screenshot 2023-09-01 at 15 38 34" src="https://github.com/Azure/terraform-azurerm-lz-vending/assets/143803576/27fdfe48-dd32-4243-9a8f-eee4bdee8239">

**Comment by Raphael-kainos** [comment]
If you need anymore clarification on what I mean let me know, Im not most experienced with terraform so might not be crystal clear.

**Comment by matt-FFFFFF** [comment]
Hi!

Yes this is possible. You use the same loop value that you use for the sub vending as you do for the other resources.

The thing is that you have to use the azapi provider as you don't know the subscription id.

**Comment by Raphael-kainos** [comment]
okay so just to clarify I can add key vault.tf , route tables.tf etc to the LZ_Vending module and get these resources to deploy to the same subscription id specified landing zone. The sub id will differ as the loop iterate, based on a object map.

<img width="752" alt="Screenshot 2023-09-05 at 23 24 48" src="https://github.com/Azure/terraform-azurerm-lz-vending/assets/143803576/cbb35127-73c2-4b58-a9ca-8f3a19f562f5">

<img width="351" alt="Screenshot 2023-09-05 at 23 35 16" src="https://github.com/Azure/terraform-azurerm-lz-vending/assets/143803576/0faaf9c1-ac04-4e54-85c7-0d8283b93341">

Have you got any resources/examples I can look at for trying to achieve this using azapi provider?

Thanks for your help

**Comment by matt-FFFFFF** [comment]
Hi, you don't modify the lz_vending module, you use its outputs.

E.g. using your example above to create a resource group in each created sub. (this is an example, and actually the module does rg creation already, the RG is just is a simple resource to use as an example).

For Key Vault use this reference: https://learn.microsoft.com/en-us/azure/templates/microsoft.keyvault/vaults?pivots=deployment-language-terraform

You can add extra data to var.landing_zones

```terraform
resource "azapi_resource" "symbolicname" {
  type      = "Microsoft.Resources/resourceGroups@2022-09-01"
  for_each  = var.landing_zones
  name      = each.value.rgname
  location  = each.value.location
  parent_id = module.landing_zones[each.key].subscription_resource_id
  body = jsonencode({
    properties = {}
  })
}
```

**Comment by Raphael-kainos** [comment]
Thanks you alot for your help!  I will give this a shot

**Comment by Raphael-kainos** [comment]
Hey Matt! Im having trouble accessing the output subscription_resource_id from the module. Im sure its something Im doing wrong. I can see the output when I dig into  .terraform /module/LZ_Vending.lz_vending directory but terraform cant access it maybe it got something to do with my directory structure?

<img width="461" alt="Screenshot 2023-09-08 at 13 39 11" src="https://github.com/Azure/terraform-azurerm-lz-vending/assets/143803576/4b73e1e3-4f27-4116-ae1c-37a5ccecfce2">
<img width="795" alt="Screenshot 2023-09-08 at 13 37 15" src="https://github.com/Azure/terraform-azurerm-lz-vending/assets/143803576/6c368f96-7bc2-4b1b-8617-1173155af250">

**Comment by Raphael-kainos** [comment]
@matt-FFFFFF  figured it out, worked like a charm, thanks for you help

**Comment by lbarrettRC** [comment]
Using the parent_id parameter assigned to each azapi resource you can link the additional resources to the subscriptions being vended. e.g.  parent_id  = "${module.lz_vending[each.key].subscription_resource_id}/resourceGroups/

**Comment by jegre** [comment]
Hi @matt-FFFFFF 
I wanted to follow up, because I am having a similar usecase. I am building a landing-zone-vending repo, where I have a tfvars for each landing-zone. With azure devops pipeline, I dynamically create a stage per subscription/landingzone.

Now, I want to add additional azure resources, that are not supported in the lz-vending module. Reading from your statement above, it is not possible to use resources from azurerm, since the subscription id is not known, and I can only use azApi resources (which I'd like to avoid).

**Comment by matt-FFFFFF** [comment]
Hi there @jegre 

As you've noticed, AzureRM needs the sub id to be known at init time. This makes it unsuitable for use in the same plan as the sub creation.

There is nothing we can do about this as this is a design decision from Hashicorp.

AzAPI is a fine provider and I wouldn't write it off.
