### ISSUE TITLE
bug: Error while creating Sub with SPN

### ISSUE THREAD

**Issue by DevanshuSyk** [Azure/terraform-azurerm-lz-vending#280]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

#######
module.lz_vending.module.subscription[0].azurerm_subscription.this[0]: Creating...
╷
│ Error: creating new Subscription (Alias "abcd"): subscriptions.SubscriptionsClient#AliasCreate: Failure sending request: StatusCode=0 -- Original Error: Code="UserNotAuthorized" Message="User is not authorized to create subscriptions on this enrollment account"
│ 
│   with module.lz_vending.module.subscription[0].azurerm_subscription.this[0],
│   on .terraform/modules/lz_vending/modules/subscription/main.tf line 2, in resource "azurerm_subscription" "this":
│    2: resource "azurerm_subscription" "this" {
│ 
Terraform v1.6.3
on darwin_arm64
+ provider registry.terraform.io/azure/azapi v1.10.0
+ provider registry.terraform.io/hashicorp/azurerm v3.79.0

{

#### Steps to Reproduce

I am trying to create  sub with the LZ-vending module .I have followed the guide and have granted permission to SPN as subscription creator how i keep getting error

**Comment by matt-FFFFFF** [comment]
Hi what sort of commercial agreement are you using? EA, MCA?

**Comment by DevanshuSyk** [comment]
Thankx for the reply .this is an EA agreement 

Here is a snippet of role granted to SPN

roleDefinitionId": "/providers/Microsoft.Billing/billingAccounts/12345/enrollmentAccounts/12344/billingRoleDefinitions/a0bcee42-bf30-4d1b-926a-48d21664ef71",
    "scope": "/providers/Microsoft.Billing/billingAccounts/12334/enrollmentAccounts/123234",
    "userAuthenticationType": "Organization"
  },
  "type": "Microsoft.Billing/billingRoleAssignments"
}

**Comment by matt-FFFFFF** [comment]
This all looks correct, as you're using a SPN - could you try this using the az cli/powershell to verify permissions are correct?

use `az login --service-principal`

then `az account alias create`

**Comment by DevanshuSyk** [comment]
just did that with postman 
{
    "id": "/providers/Microsoft.Subscription/aliases/001",
    "name": "001",
    "type": "Microsoft.Subscription/aliases",
    "properties": {
        "subscriptionId": "98152c1e-6ed4-40d5-b970-5c1b02d42717",
        "provisioningState": "Accepted"
    }
}

**Comment by DevanshuSyk** [comment]
and here is output of Az cli 


{
  "id": "/providers/Microsoft.Subscription/aliases/TEst001",
  "name": "TEst001",
  "properties": {
    "acceptOwnershipState": null,
    "acceptOwnershipUrl": null,
    "billingScope": null,
    "createdTime": null,
    "displayName": null,
    "managementGroupId": null,
    "provisioningState": "Succeeded",
    "resellerId": null,
    "subscriptionId": "931e5eae-fc2f-4913-b2d0-94781d636e8c",
    "subscriptionOwnerId": null,
    "tags": null,
    "workload": null
  },
  "systemData": null,
  "type": "Microsoft.Subscription/aliases"
}

**Comment by DevanshuSyk** [comment]
The pushed a new config and the problem vanished .I literally didn't changed anything  :)

Thank for the help .

**Comment by matt-FFFFFF** [comment]
Glad you are unblocked 👍
