### ISSUE TITLE
feat: Role Assignment with Conditions

### ISSUE THREAD

**Issue by tcharewicz** [Azure/terraform-azurerm-lz-vending#282]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

I would like to create Role Assignment with Condition, currently terraform resource allow for this operation

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment

Description of this variable on resource:
[condition](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment#condition) - (Optional) The condition that limits the resources that the role can be assigned to. Changing this forces a new resource to be created.

[condition_version](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment#condition_version) - (Optional) The version of the condition. Possible values are 1.0 or 2.0. Changing this forces a new resource to be created.

### Describe the solution you'd like

Add additional variables condition and condition_version to role_assignment map. Example below:

```
module "lz_vending" {
  source  = "Azure/lz-vending/azurerm"
  version = "<version>" # change this to your desired version, https://www.terraform.io/language/expressions/version-constraints

  # Set the default location for resources
  location = "westeurope"

 <cut>

  # role assignments
  role_assignment_enabled = true
  role_assignments = {
    # using role definition name, created at subscription scope
    contrib_user_sub = {
      principal_id   = "00000000-0000-0000-0000-000000000000"
      definition     = "Contributor"
      relative_scope = ""
      condition_version = "2.0" <-- version of condition passed to resource in sub-module.
      condition = {}  <-- map of confitions passed to resource in sub-module
    }
  }
}
```

**Comment by matt-FFFFFF** [comment]
Hi! This is a good ask. We will look into it and prioritize

**Comment by tcharewicz** [comment]
I can contribute to repository and create Pull Request with required changes. If that help?

**Comment by matt-FFFFFF** [comment]
Thank you for the offer that would be fantastic!

**Comment by tcharewicz** [comment]
https://github.com/Azure/terraform-azurerm-lz-vending/pull/285

**Comment by matt-FFFFFF** [comment]
Closing as merged into main now and will be in next minor release

**Comment by knuterik-ballestad** [comment]
@matt-FFFFFF :
Do you have any plans to implement the same for Entra Id Privileged Identity Management?
 - so that we can assign and set conditions also to Entra ID role assignments?

**Comment by matt-FFFFFF** [comment]
Hi,

Thanks for the question. We don't have plans for this in this module. It seems that this falls outside the scope of the subscription vend process - although this feature can be orchestrated using the module outputs if required.

**Comment by knuterik-ballestad** [comment]
OK.

We were planning to use Azure roles for "DevTest" type subscriptions, and Entra Id PIM roles for "Production" type subscriptions, but we can live with using conditions on Azure roles if we have to.

Thanks for answering!
