### ISSUE TITLE
bug: documentation not correct

### ISSUE THREAD

**Issue by laingsc** [Azure/terraform-azurerm-lz-vending#297]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

TF: 1.6.3
Module: 3.4.1

### Description
Regarding secure_internet_traffic not being compatible with routing intent.  It actually is the only thing you can configure in addition to routing intent.  From the Azure Firewall Manager 'Security configuration' page: "Manage internet and private security configuration for hub connections. Internet security configuration can be updated selectively for individual connections. Private traffic security configuration must collectively secure all/no connections."

I've had to do this for my Azure Bastion Virtual Hub extension, as it needs to go direct and not via Firewall.  Enabling routing intent, and configuring for internet and private traffic, will force private traffic via the Firewall for any connected vnets and branches, but does not automatically force internet traffic to the firewall.

"secure_internet_traffic: Whether to forward internet-bound traffic to the destination specified in the routing policy. Not compatible with routing_intent_enabled. [optional - default false]"

#### Steps to Reproduce

This is my current set up outside of this module and it works well:

Here's two different vhub connections, one with internet_security_enabled = true and the other false:

```
resource "azurerm_virtual_hub_connection" "dns_hub_extension" {
  name                      = "cnn01-network-vnet-connection"
  remote_virtual_network_id = azurerm_virtual_network.hub_dns_extension.id
  virtual_hub_id            = azurerm_virtual_hub.australiaeast_vhub.id
  internet_security_enabled = true
}

resource "azurerm_virtual_hub_connection" "no_internet_firewall" {
  name                      = "cnn01-no-internet-vnet-connection"
  remote_virtual_network_id = azurerm_virtual_network.no_internet_firewall.id
  virtual_hub_id            = azurerm_virtual_hub.australiaeast_vhub.id
  internet_security_enabled = false
}

Additionally, here's my routing intent:
resource "azurerm_virtual_hub_routing_intent" "australiaeast_vhub" {
  name           = "cnn01-ent-central-vwan-ri"
  virtual_hub_id = azurerm_virtual_hub.australiaeast_vhub.id
  routing_policy {
    name         = "InternetTrafficPolicy"
    destinations = ["Internet"]
    next_hop     = azurerm_firewall.australiaeast_vhub.id
  }
  routing_policy {
    name         = "PrivateTrafficPolicy"
    destinations = ["PrivateTraffic"]
    next_hop     = azurerm_firewall.australiaeast_vhub.id
  }
}
```
#### Screenshots

This image shows two vnet connections that aren't going through the firewall.  One was intentional and the other configured through this module, which should go through the firewall...

![image](https://github.com/Azure/terraform-azurerm-lz-vending/assets/34560781/bb69a086-17df-4c1a-bbb3-b91590455c6e)

#### Additional context

Tnx!

**Comment by laingsc** [comment]
Apologies, it did actually work despite the module documentation saying otherwise...

```
      vwan_security_configuration = {
        routing_intent_enabled  = true
        secure_internet_traffic = true
      }
```

**Comment by matt-FFFFFF** [comment]
Thanks for highlighting the documentation error
