### ISSUE TITLE
bug: dependency on resource provider registration in virtual network module

### ISSUE THREAD

**Issue by rybal06** [Azure/terraform-azurerm-lz-vending#304]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/azure/azapi v1.11.0
+ provider registry.terraform.io/hashicorp/azurerm v3.85.0
+ provider registry.terraform.io/hashicorp/time v0.10.0
```

Please enter the module version that you are using:

```
3.4.2
```

#### Steps to Reproduce

Use this configuration and run terraform init, plan, and apply.
```hcl
module "lz_vending" {
  source  = "./module"
  for_each = local.landing_zone_data_map

  location = each.value.location

  # subscription variables
  subscription_alias_enabled = true
  subscription_billing_scope = "<OMITTED>"
  subscription_display_name  = each.value.name
  subscription_alias_name    = each.value.name
  subscription_workload      = each.value.workload
  subscription_register_resource_providers_enabled = true

  network_watcher_resource_group_enabled = false

  # management group association variables
  subscription_management_group_association_enabled = true
  subscription_management_group_id                  = each.value.management_group_id

  # virtual network variables
  virtual_network_enabled = true
  virtual_networks        = each.value.virtual_networks
}
```
The Terraform plan shows creating the provider registrations:

```text
module.lz_vending["lz1.json"].module.resourceproviders["Microsoft.Network"].azapi_resource_action.resource_provider_registration will be created
  + resource "azapi_resource_action" "resource_provider_registration" {
      + action      = "providers/Microsoft.Network/register"
      + id          = (known after apply)
      + method      = "POST"
      + output      = (known after apply)
      + resource_id = "/subscriptions/<omitted>"
      + type        = "Microsoft.Resources/subscriptions@2021-04-01"
      + when        = "apply"
    }

```

However Terraform is trying to create the virtual network in the subscription before completing provider registrations which is resulting in this problem:

```text
│ Error: creating/updating "Resource: (ResourceId \"/subscriptions/<omitted>/resourceGroups/1-tst-net-rg/providers/Microsoft.Network/virtualNetworks/1-tst-vnet\" / Api Version \"2021-08-01\")": PUT https://management.azure.com/subscriptions/<omitted>resourceGroups/1-tst-net-rg/providers/Microsoft.Network/virtualNetworks/1-tst-vnet
│ --------------------------------------------------------------------------------
│ RESPONSE 409: 409 Conflict
│ ERROR CODE: MissingSubscriptionRegistration
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "MissingSubscriptionRegistration",
│     "message": "The subscription is not registered to use namespace 'Microsoft.Network'. See https://aka.ms/rps-not-found for how to register subscriptions.",
│     "details": [
│       {
│         "code": "MissingSubscriptionRegistration",
│         "target": "Microsoft.Network",
│         "message": "The subscription is not registered to use namespace 'Microsoft.Network'. See https://aka.ms/rps-not-found for how to register subscriptions."
│       }
│     ]
│   }
│ }

```

**Comment by rybal06** [comment]
I went through the dependency tree and made changes which ensure provider registration happens before trying to deploy the virtual network:
### Changes

main.virtualnetwork.tf:
```hcl
module "virtualnetwork" {
  source           = "./modules/virtualnetwork"
  count            = var.virtual_network_enabled ? 1 : 0
  subscription_id  = local.subscription_id
  virtual_networks = var.virtual_networks
  location         = var.location

  depends_on = [
    module.resourcegroup_networkwatcherrg,
  +  module.resourceproviders,
  ]
}
```

main.resourceproviders.tf:
```hcl
module "resourceproviders" {
  source            = "./modules/resourceprovider"
  for_each          = { for k, v in var.subscription_register_resource_providers_and_features : k => v if var.subscription_register_resource_providers_enabled }
  resource_provider = each.key
  features          = each.value
  subscription_id   = local.subscription_id

  depends_on = [
    module.subscription
  - module.virtualnetwork,
  - module.roleassignment,
  - module.usermanagedidentity
  - module.resourcegroup
  - module.roleassignment_umi
  ]
}
```

### Why this doesn't fully solve the problem

My goal is to be able to deploy a subscription landing zone and the resources inside of that subscription in a single Terraform apply. az_api_action (used for provider registration) doesn't have a mechanism to wait until provider registration is complete, so still the module attempts to deploy the virtual network before the Microsoft.Network provider is fully registered. Provider registration is an async API call, and azapi_update_resource doesn't seem to be able to account for this.

There is an open issue on az_api for this scenario: <https://github.com/Azure/terraform-provider-azapi/issues/366>

Likely could do some workaround using a provisioner or api call to work around this, but it has me questioning the approach of deploying a subscription based landing zone including resources inside of the subscription in a single terraform apply.

### Questions

Is it a recommended pattern to deploy an entire landing zone (subscription with resources) in a single terraform apply? 

It doesn't seem possible (today) in using this module, and it also isn't possible with azurerm due to <https://github.com/hashicorp/terraform-provider-azurerm/issues/17979#issuecomment-1457783514>

What is a recommended pattern? Do most customers manually deploy a subscription and then use Terraform to manage the landing zone components within?

**Comment by matt-FFFFFF** [comment]
The azure sdk for go, which azapi uses, will register providers for resources that it is deploying at the time of deployment. This is why the RP registration is left until last. It's to register any providers that are required for use later.

**Comment by rybal06** [comment]
Thanks for the quick response Matt! I knew I must have been missing something...

Might this issue indicate that the azure go sdk is not registering the Microsoft.Network as expected upon this landing zone module making the API request to deploy a virtual network?

```
 Error: creating/updating "Resource: (ResourceId \"/subscriptions/<omitted>/resourceGroups/1-tst-net-rg/providers/Microsoft.Network/virtualNetworks/1-tst-vnet\" / Api Version \"2021-08-01\")": PUT https://management.azure.com/subscriptions/<omitted>resourceGroups/1-tst-net-rg/providers/Microsoft.Network/virtualNetworks/1-tst-vnet
│ --------------------------------------------------------------------------------
│ RESPONSE 409: 409 Conflict
│ ERROR CODE: MissingSubscriptionRegistration
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "MissingSubscriptionRegistration",
│     "message": "The subscription is not registered to use namespace 'Microsoft.Network'. See https://aka.ms/rps-not-found for how to register subscriptions.",
│     "details": [
│       {
│         "code": "MissingSubscriptionRegistration",
│         "target": "Microsoft.Network",
│         "message": "The subscription is not registered to use namespace 'Microsoft.Network'. See https://aka.ms/rps-not-found for how to register subscriptions."
│       }
│     ]
│   }
│ }
```

**Comment by matt-FFFFFF** [comment]
You can see in [this file](https://github.com/Azure/azure-sdk-for-go/pull/20848/files#diff-f24639de2c5e86d5974dbfdd9b3b0843202304f0eb641c095924488910b8f13b) the registration process. You should be able to see log messages for provider registration.

Can you set `TF_LOG_PROVIDER=trace` and retry the operation?

**Comment by matt-FFFFFF** [comment]
@rybal06 Please see this comment: https://github.com/Azure/terraform-azurerm-lz-vending/issues/314#issuecomment-1906465482

Have you disabled provider registration using an environment variable?

**Comment by rybal06** [comment]
Apologies about the delay - you are exactly correct. The env to disable azurerm provider registration is in our pipeline template as default, and I had thought initially because this module uses az_api that env var was ignored. Sorry about the inconvenience and thanks for the response!

Ultimately, we went a different direction. We had to make a decision about whether to use this repo (which relies on az_api) or to build a complex CICD process to work around azure_rm not supporting deploying a subscription with resources inside of it in a single Terraform operation and not easily supporting managing resources in multiple subscriptions without using provider blocks and aliases. 

Ultimately, we decided the challenges of az_api outweighed the challenges of a complex CICD process and we have a similar solution to this repo working using azure_rm instead. We have one state file per subscription to work around needing provider aliases, and use item level targeting to deploy the subscription independently of the resources within a stage prior to managing the rest of the resources.

I want to thank the team behind this repo! We learned new Terraform tricks and concepts; and the organization very much inspired our own design. It was incredibly valuable to see how things are designed in this repo, and how you overcame certain challenges we faced.

**Comment by matt-FFFFFF** [comment]
No worries glad you worked around the issue in the end!

There is a simple workaround though,

You can explicitly set provider registration in your config for just the azapi provider - it will then only register the ones it needs.

```terraform
provider "azapi" {
  skip_provider_registration = false
}
