### ISSUE TITLE
bug: no tags deployed with NetworkWatcherRG

### ISSUE THREAD

**Issue by craigmoyle** [Azure/terraform-azurerm-lz-vending#305]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
1.6.5
```

Please enter the module version that you are using:

```text
3.4.2
```

#### Steps to Reproduce

1. Deploy a subscription with `network_watcher_resource_group_enabled` set to true
2. Check Resource Group
3. No tags are created

#### Additional context

This also affects the deployment in Production as there's an Azure Policy to deny creation of Resource Groups without tags. This would be similar in many companies.

To fix I think we just need to update `main.resourcegroup.tf` from

```
module "resourcegroup_networkwatcherrg" {
  source              = "./modules/resourcegroup"
  count               = var.network_watcher_resource_group_enabled ? 1 : 0
  subscription_id     = local.subscription_id
  location            = var.location
  resource_group_name = "NetworkWatcherRG"
  tags                = {}
}
```

to 

```
module "resourcegroup_networkwatcherrg" {
  source              = "./modules/resourcegroup"
  count               = var.network_watcher_resource_group_enabled ? 1 : 0
  subscription_id     = local.subscription_id
  location            = var.location
  resource_group_name = "NetworkWatcherRG"
  tags                = var.tags
}
```

Unless there's a reason why tags on a NetworkWatcherRG shouldn't be enabled.

**Comment by matt-FFFFFF** [comment]
Hi.

This looks like a big yes. Will investigate.

**Comment by matt-FFFFFF** [comment]
Confirmed bug:

https://github.com/Azure/terraform-azurerm-lz-vending/blob/47d074dae3e69f54de3d890d1b27c56603a8addd/main.resourcegroup.tf#L18

**Comment by matt-FFFFFF** [comment]
Actually sorry,

This is not a bug.

If you want to put tags on the NetworkWatcherRG, then include it in `var.resource_groups` and set `var.network_watcher_resource_group_enabled` to false

**Comment by craigmoyle** [comment]
Thanks Matt, tbh we were doing that before this feature was added so I'm confused as to the use case for this feature now.

**Comment by matt-FFFFFF** [comment]
The feature to manage networkwatcherrg predates the feature to manage a set of RGs. 

The latter feature is more flexible and has support for tags per rg.
