### ISSUE TITLE
bug:  subscription_use_azapi not available on  version 3.4.2

### ISSUE THREAD

**Issue by leandro-borges-djd** [Azure/terraform-azurerm-lz-vending#306]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
Terraform v1.4.2
on windows_386
+ provider registry.terraform.io/azure/azapi v1.11.0
+ provider registry.terraform.io/hashicorp/azurerm v3.85.0
```

Please enter the module version that you are using:

```text
Downloading registry.terraform.io/Azure/lz-vending/azurerm 3.4.2 for lz_vending.lz_vending...
```

#### Steps to Reproduce

terraform validate
╷
│ Error: Unsupported argument
│
│   on modules\lz_vending\lz_vending.tf line 10, in module "lz_vending":
│   10:   subscription_use_azapi = true
│
│ An argument named "subscription_use_azapi" is not expected here.

#### Screenshots

![image](https://github.com/Azure/terraform-azurerm-lz-vending/assets/154548717/06ec7850-b4b7-473e-9f5b-7a3e0a66bbb6)

**Comment by leandro-borges-djd** [comment]
Well, I believe the README file of the repo is not synched with the modules,

![image](https://github.com/Azure/terraform-azurerm-lz-vending/assets/154548717/b42847ea-fab5-4e09-82e8-10326c6df3ad)

**Comment by matt-FFFFFF** [comment]
Hi,

This isn't a bug. We haven't released the AzAPI stuff yet.

I recommend reviewing the module documentation in the hashicorp registry as it is tagged to the release versions.
