### ISSUE TITLE
bug: VirtualNetwork module not dependent on ResourceProvider module. 

### ISSUE THREAD

**Issue by kristeey** [Azure/terraform-azurerm-lz-vending#314]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

`terraform_version: 1.6.6`
```
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.81"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "2.46.0"
    }
    azapi = {
      source  = "azure/azapi"
      version = "1.9.0"
```
`Azure/lz-vending/azurerm` version `v3.4.1`

### Description
The Virtual Network module should be dependent on the Resource Provider module as it needs the `Microsoft.Network` resource provider to be able to provision network infra. As of now terraform apply will sometimes fail if the resource providers isn't applied before the Vnet resources gets created (dependent on the order things gets applied due to parallelism). 

#### Steps to Reproduce

1. step 1:
Configure the Landing zone module with the following
```
  subscription_register_resource_providers_enabled           = true
  subscription_register_resource_providers_and_features  = { "Microsoft.Network": [] }
```
2. step 2
terraform init -> plan -> apply
3. Terraform failes if the resource providers isn't applied before the virtual network module

#### Screenshots

```
Error: creating/updating "Resource: (ResourceId \"/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/xxx\" / Api Version \"2021-08-01\")": PUT https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/xxx
--------------------------------------------------------------------------------
RESPONSE 409: 409 Conflict
ERROR CODE: MissingSubscriptionRegistration
--------------------------------------------------------------------------------
{
  "error": {
    "code": "MissingSubscriptionRegistration",
    "message": "The subscription is not registered to use namespace 'Microsoft.Network'. See https://aka.ms/rps-not-found for how to register subscriptions.",
    "details": [
      {
        "code": "MissingSubscriptionRegistration",
        "target": "Microsoft.Network",
        "message": "The subscription is not registered to use namespace 'Microsoft.Network'. See https://aka.ms/rps-not-found for how to register subscriptions."
      }
    ]
  }
}
--------------------------------------------------------------------------------
```

**Comment by matt-FFFFFF** [comment]
Hi, as per #304 this is not correct. The AzAPI provider will register RPs as it needs them via the Go SDK.

Please can you run provider trace to understand why this isn't happening.

**Comment by kristeey** [comment]
I belive this is due to that the `azurerm` provider is configured with the `skip_provider_registration: true` flag (which is desirable since the `azurerm` will otherwise registre all resource providers, going against the least privilege principle). By configuring this flag I belive the `ARM_SKIP_PROVIDER_REGISTRATION: true` environment variable is set, which then will affect the `azapi` provider as well. I can verify from the logs from my runner that the environment variable was set upon runtime of terraform apply.

**Comment by matt-FFFFFF** [comment]
@kristeey 

Were you setting this env var in your configuration?

You are right that AzAPI also uses the same env var as AzureRM:

https://github.com/Azure/terraform-provider-azapi/blob/f4d4045f609cdd2053139b24eac57f6c9dbd5736/internal/provider/provider.go#L147-L152

This is then passed into the client options here:

https://github.com/Azure/terraform-provider-azapi/blob/f4d4045f609cdd2053139b24eac57f6c9dbd5736/internal/provider/provider.go#L366

Which is then passed into the Go SDK for Azure here:

https://github.com/Azure/terraform-provider-azapi/blob/f4d4045f609cdd2053139b24eac57f6c9dbd5736/internal/clients/client.go#L104

You can try explicitly setting `skip_provider_registration=false` like this:

```terraform
provider "azapi" {
  skip_provider_registration = false
}
```

This should override the env var

**Comment by kristeey** [comment]
Looks like this env var is already set in the runner before running the terraform commands. I will try to explicitly set 
```
provider "azapi" {
  skip_provider_registration = false
}
```
the next time I run the script.

**Comment by kristeey** [comment]
Just to clarify. This `azapi` flag do not registre all resource providers the way `azurerm` does, only the ones it needs to provision the `azapi` resources in the configuration files?

**Comment by matt-FFFFFF** [comment]
> Just to clarify. This `azapi` flag do not registre all resource providers the way `azurerm` does, only the ones it needs to provision the `azapi` resources in the configuration files?

Correct, it only does the ones that it needs to make an API call :)

**Comment by kristeey** [comment]
I can confirm that after doing the changes it works without problems for me. Just for the record: 
 In addition having 
```
provider "azapi" {
  skip_provider_registration = false 
}
provider "azurerm" {
  tenant_id                  = var.tenant_id
  subscription_id            = var.subscription_id
  skip_provider_registration = true 
  features {}
}
```
to the provider configuration, I removed the `ARM_SKIP_PROVIDER_REGISTRATION: true` environment variable from my running environment.

**Comment by sioakim** [comment]
Thank you for this
Indeed I did have skip_provider_registration = true
Changed it to false and all worked like a charm

Please close this :)
