### ISSUE TITLE
bug: subscription_tags in Yaml Data file

### ISSUE THREAD

**Issue by aristdm** [Azure/terraform-azurerm-lz-vending#321]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
<output of terraform version>
```

Please enter the module version that you are using:

```text
3.4.2
```

#### Steps to Reproduce

Apologies for my ignorance in advance as I explore terraform world. I'm trying to streamline the subscription vending process, and using the example 3 provided with use of Yaml data file for multiple subscription vending. I would like to add specific subscription_tags to each subscription during the provisioning process and make use of Azure Policy to enable inheritance. 

The Terraform Plan is failing with "This object does not have an attribute named subscription_tags". Maybe my syntax in the yaml file is wrong or there is something wrong with defining the subscription_tags in the main.tf file? Any help would be appreciated. 

#lxx-gen-corp-001.yaml

subscription_tags:
      - mytag: "myvalue"
      - mytag2: "myvalue2"

#main.tf

 #subscription variables
  subscription_alias_enabled = true
  subscription_billing_scope = "/providers/Microsoft.Billing/billingAccounts/xxxxxx/enrollmentAccounts/${each.value.billing_enrollment_account}"
  subscription_display_name  = each.value.name
  subscription_alias_name    = each.value.name
  subscription_workload      = each.value.workload
  subscription_tags          = each.value.subscription_tags

#### Screenshots
Planning failed. Terraform encountered an error while generating this plan.

#Output
╷
│ Error: Invalid value for input variable
│ 
│   on main.tf line 17, in module "lz_vending":
│   17:   subscription_tags          = each.value.subscription_tags
│ 
│ The given value is not suitable for
│ module.lz_vending["../../xxx-landing-zones/xx/xx-gen-corp-001.yaml"].var.subscription_tags
│ declared at
│ .terraform/modules/lz_vending/variables.subscription.tf:134,1-29: map of
│ string required.
╵
╷
│ Error: Unsupported attribute
│ 
│   on main.tf line 17, in module "lz_vending":
│   17:   subscription_tags          = each.value.subscription_tags
│     ├────────────────
│     │ each.value is object with 7 attributes
│ 
│ This object does not have an attribute named "subscription_tags".
╵

#### Additional context

Let me know if this is not the right place to raise this, but I think it would be helpful to other people as well.

**Comment by matt-FFFFFF** [comment]
Try this:


```yaml
subscription_tags:
  mytag: "myvalue"
  mytag2: "myvalue2"
```

**Comment by aristdm** [comment]
Hi Matt, 

I've tried that already in the main.tf file and it works but that would be same tags for all subscriptions (static tags). The idea is to use the input data from the landing_zone YAML data file as variables (see example 3 in wiki), as every subscription might have different tags (i.e different Cost Center, Owner etc exactly like vnet, role_assignment etc works).

I've done some further digging,  and it looks like the locals.tf uses yamldecode to parse the data, I'm suspecting if this doesn't play nice with parsing map(string) type of data that subscription_tags requires. 

Any idea how to properly define the tags in each landing_zone.yaml file and then parse the data to subscription_tags {} in the main.tf (module "lz_vending" ? Appreciate the help.

**Comment by aristdm** [comment]
> Try this:
> 
> ```yaml
> subscription_tags:
>   mytag: "myvalue"
>   mytag2: "myvalue2"
> ```

**main.tf**

#The landing zone module will be called once per landing_zone_*.yaml file
#in the data directory.
module "lz_vending" {
  source   = "Azure/lz-vending/azurerm"
  version  = "3.4.2"
  disable_telemetry = true
  for_each = local.landing_zone_data_map

  location = each.value.location

  #subscription variables
  subscription_alias_enabled = true
  subscription_billing_scope = "/providers/Microsoft.Billing/billingAccounts/xxxxxx/enrollmentAccounts/${each.value.billing_enrollment_account}"
  subscription_display_name  = each.value.name
  subscription_alias_name    = each.value.name
  subscription_workload      = each.value.workload
  **subscription_tags          = each.value.subscription_tags**

  #network_watcher_resource_group_enabled = true

  #Turn off RP registration in this test
  subscription_register_resource_providers_and_features = {}

  #management group association variables
  subscription_management_group_association_enabled = true
  subscription_management_group_id                  = each.value.management_group_id

  #virtual network variables
  virtual_network_enabled = true
  virtual_networks        = each.value.virtual_networks

  #role assignment variables
  role_assignment_enabled = true
  role_assignments        = each.value.role_assignments
}`

**Comment by aristdm** [comment]
closing this one as this was working as expected

in the main.tf file you need to assign
`subscriptions_tags = each.value.subscriptions_tags`

in the yaml data files you need to configure. You need to do this for each landing zone yaml file.
`subscription_tags:
tag1: myvalue
tag2: myvalue2`
