### ISSUE TITLE
bug: Can no longer create UMI Role Assignments in v4.0.0

### ISSUE THREAD

**Issue by birdnathan** [Azure/terraform-azurerm-lz-vending#323]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

![image](https://github.com/Azure/terraform-azurerm-lz-vending/assets/42775203/50279924-1120-49c2-8dd2-39253462fc0c)

### Description

![image](https://github.com/Azure/terraform-azurerm-lz-vending/assets/42775203/f4574e8a-09ab-4fcc-bbb1-b0266beaa97a)

![image](https://github.com/Azure/terraform-azurerm-lz-vending/assets/42775203/0ae3ee9d-fefb-42c5-8f0f-e40dfb41edf4)

Probably related to https://github.com/Azure/terraform-azurerm-lz-vending/pull/285 @tcharewicz 

No issues in v3.4.2

**Comment by matt-FFFFFF** [comment]
Thanks @birdnathan 

Looks like a slip up. Leave it with us
