### ISSUE TITLE
feat: change subscription_alias_name to optional

### ISSUE THREAD

**Issue by walkafwalka** [Azure/terraform-azurerm-lz-vending#328]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

**Is your feature request related to an issue?**

Currently, `subscription_alias_name` is a required variable when `subscription_alias_enabled` is enabled. In cases where you might want to rename the alias, you can change `subscription_display_name`, but `subscription_alias_name` cannot be changes with a destroy/create. The native `azurerm_subscription` makes the `alias` parameter optional, and instead generates its own UUID.

### Describe the solution you'd like

Change `subscription_alias_name` to an optional variable when `subscription_alias_enabled` is true.

**Comment by walkafwalka** [comment]
Yes, I could, but then the alias_name has a readable name that may conflict with the display name as opposed to a generic UUID.

**Comment by matt-FFFFFF** [comment]
I see. In that case it would be possible to supply a UUID for the alias name in the first instance, correct?
