### ISSUE TITLE
bug: hub_peering_direction not initiating peering

### ISSUE THREAD

**Issue by walkafwalka** [Azure/terraform-azurerm-lz-vending#329]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
Terraform v1.6.4
on linux_amd64
+ provider registry.terraform.io/azure/azapi v1.12.0
+ provider registry.terraform.io/hashicorp/azurerm v3.91.0
+ provider registry.terraform.io/hashicorp/time v0.10.0
```

Please enter the module version that you are using:

```text
4.0.1
```

#### Steps to Reproduce

Enable hub peering and set `hub_peering_direction = "fromhub"`. It only creates an inbound peering without an outbound peering, which causing the peering to be stuck in "initiated". However, it should create both an inbound and outbound peering with the outbound peering `allowVirtualNetworkAccess` and other settings set to false.

#### Screenshots

![image](https://github.com/Azure/terraform-azurerm-lz-vending/assets/41709139/5bc47e80-dac9-4a33-93e1-c522f3f72376)

**Comment by jaredfholgate** [comment]
Hi @walkafwalka and @matt-FFFFFF. This is not the point of that setting. That setting for the purpose of initiating the peering on one side with subscription vending and then having a separate mechanism to complete the peering in a separate terraform module, such as hub networking. This is about segregation of roles required by some organisations.

Adding your fix breaks this as it attempts to add the peeing on the other VNET that it does not have permissions for. If you are trying to alter the allowed traffic flows that would need to be an update the `both` option. 

It may be possible to achieve what you want already with configuration settings. If not, then we could add configuration to allow it instead, but would have to be on the `both` option.

**Comment by walkafwalka** [comment]
Ah, I see. With the additional context, I understand. I believe
