### ISSUE TITLE
bug: creating subscription with invalid character in tag value

### ISSUE THREAD

**Issue by ChrisSidebotham** [Azure/terraform-azurerm-lz-vending#332]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
Terraform v1.7.0
```

Please enter the module version that you are using:

```text
4.0.0
```

### Description

When using `subscription_tags` with `subsciption_alias_enabled` no validation is done on tags (Azure does not allow the following characters: `<>%&\?/.`). Therefore, when the deployment runs to create the subscription, if the tag contains an invalid character the deployment fails and the terraform state does not save the state of the newly created subscription alias. Requireing you to either:
- Generate a new subscription name (most customers have naming conventions making this difficult) 
- Remove the resource (Production subscriptions take 7 days to cancel)
- Import the resource to the state (Not CI/CD Friendly for most customer)

#### Steps to Reproduce

1. supply the following tag `Internal / External` 
2. attempt to run the vend with `subscription_alias_enabled`
3. you get it...

#### Screenshots

![image](https://github.com/Azure/terraform-azurerm-lz-vending/assets/48600046/029f7b50-ae28-4aa7-9616-1a69934eedcd)

**Comment by matt-FFFFFF** [comment]
Nice catch. Thanks will add the validation rule
