### ISSUE TITLE
bug: Resources are created before the subscription is fully in the destination management group

### ISSUE THREAD

**Issue by djbark** [Azure/terraform-azurerm-lz-vending#337]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
Terraform v1.6.6
on linux_amd64
+ provider registry.terraform.io/azure/azapi v1.12.0
+ provider registry.terraform.io/hashicorp/azurerm v3.87.0
+ provider registry.terraform.io/hashicorp/time v0.10.0
```

Please enter the module version that you are using:

```text
4.0.1
```

### Description

The default subs area within our tenant is restricted and no resources can be created in any subscriptions located within it.  It appears that subscriptions do end up in the defined management group but they pass through the default subs area.  Unfortunately the creation of resources (eg vnets) is whilst the subscription is in the default subs area.  This is blocked and hence the terraform deploy doesn't fully work.  If the terraform plan/deploy is run a second time it creates the resources.

I do not want to unrestrict our default subs area so am considering just creating the empty subscription first, then adding resources to it afterwards if this issue can not fixed.

#### Steps to Reproduce

1. Restrict the default subs area
2. Create a subscription with new resources (eg vnets) included in the module

**Comment by matt-FFFFFF** [comment]
Hi @djbark - have you tried using the new subscription_use_azapi option?

This will create the subscription directly in the specified management group, instead of moving it.

/cc @luke-taylor

**Comment by djbark** [comment]
> Hi @djbark - have you tried using the new subscription_use_azapi option?
> 
> This will create the subscription directly in the specified management group, instead of moving it.
> 
> /cc @luke-taylor

I hadn't.  It works fine.  Thanks for your quick response.

**Comment by matt-FFFFFF** [comment]
Awesome!
