### ISSUE TITLE
feat: add an additional flag to deploy default resource providers

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-lz-vending#349]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

**Is your feature request related to an issue?**

When calling the vending module, there are two variables that control resource providers:

``subscription_register_resource_providers_enabled``
``subscription_register_resource_providers_and_features``

I would like a mechanism to deploy the defaults but I can't see a way to do this in a generic way.

Lets assume you pass it via a var:

```terraform
module "lz_vending" {
  source   = "Azure/lz-vending/azurerm"
  version  = "4.0.2"
  for_each = local.landing_zone_data_map

  # resource providers
  subscription_register_resource_providers_and_features = var.resource_providers
```

This would allow you to specify no resource providers (``{}``) or a map - but there's no option that means "use the default setting"

In order to use the default, i'd need to replicate that default value in the root module code.

### Describe the solution you'd like

One possible way to accomplish this would be to have a flag:

```terraform
variable "subscription_register_resource_providers_defaults" {
  type        = bool
  description = <<DESCRIPTION
Whether to register the default set of resource providers for the subscription.
DESCRIPTION
  default     = false
}

locals {
  subscription_register_resource_providers = var.subscription_register_resource_providers_defaults ? 
  {
        "Microsoft.ApiManagement"           = [],
        "Microsoft.AppPlatform"             = [],
        # etc
  } 
  : var.subscription_register_resource_providers_and_features
}

```

Thoughts on this approach?  Am I missing an obvious way to do this more cleanly?

**Comment by jaredfholgate** [comment]
@kewalaka You just need to set `subscription_register_resource_providers_enabled` to `true` and not set a value for `subscription_register_resource_providers_and_features` to use the defaults. I'm not sure if I am missing something here?

**Comment by matt-FFFFFF** [comment]
@kewalaka 

Can you set it to `null` in the YAML?

**Comment by kewalaka** [comment]
> @kewalaka
> 
> Can you set it to `null` in the YAML?

holy moly, how does that work...

```yaml
# the yaml snippet
resource_providers_enabled: true
```

terraform snippet:

```terraform
module "lz_vending" {
  source = "git::https://github.com/kewalaka/terraform-azurerm-lz-vending?ref=feat/add-rg-dependency"
  # version  = "4.1.0"
  for_each = local.landing_zone_data_map

  <snip/>

  # resource providers
  subscription_register_resource_providers_enabled      = try(each.value.resource_providers_enabled, null) == null ? false : each.value.resource_providers_enabled
  subscription_register_resource_providers_and_features = try(each.value.resource_providers_and_features, null)

  <snip/>
}
```

but i thought nullable=false meant you can't assign null?  🤯

thanks though @matt-FFFFFF , that works perfectly

![image](https://github.com/Azure/terraform-azurerm-lz-vending/assets/3146590/6f6f328f-3577-4ada-84f1-942f69cf43fc)

**Comment by jaredfholgate** [comment]
> > @kewalaka
> > Can you set it to `null` in the YAML?
> 
> holy moly, how does that work...
> 
> ```yaml
> # the yaml snippet
> resource_providers_enabled: true
> ```
> 
> terraform snippet:
> 
> ```terraform
> module "lz_vending" {
>   source = "git::https://github.com/kewalaka/terraform-azurerm-lz-vending?ref=feat/add-rg-dependency"
>   # version  = "4.1.0"
>   for_each = local.landing_zone_data_map
> 
>   <snip/>
> 
>   # resource providers
>   subscription_register_resource_providers_enabled      = try(each.value.resource_providers_enabled, null) == null ? false : each.value.resource_providers_enabled
>   subscription_register_resource_providers_and_features = try(each.value.resource_providers_and_features, null)
> 
>   <snip/>
> }
> ```
> 
> but i thought nullable=false meant you can't assign null? 🤯
> 
> thanks though @matt-FFFFFF , that works perfectly
> 
> ![image](https://private-user-images.githubusercontent.com/3146590/323123923-6f6f328f-3577-4ada-84f1-942f69cf43fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTkxNTAsIm5iZiI6MTcxMzM1ODg1MCwicGF0aCI6Ii8zMTQ2NTkwLzMyMzEyMzkyMy02ZjZmMzI4Zi0zNTc3LTRhZGEtODRmMS05NDJmNjljZjQzZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTdUMTMwMDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGNhYjE5YTg5OTg5MGQ0ZDBmNWM2NDU5Y2I3NzdkMWE4M2FiYjU1OWE0ODdlN2FlYWU0OTA3MDA2ZjZlNDJmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8LwCT-3FwoXuSs6nptYsWHaHAcpcd0U1R7U1L57v2ac)

Per the docs: https://developer.hashicorp.com/terraform/language/values/variables#disallowing-null-input-values

> If nullable is false and the variable has a default value, then Terraform uses the default when a module input argument is null.
