### ISSUE TITLE
feat: Azure Terraform SRE - formerly CAF Terraform Add-On Module support

### ISSUE THREAD

**Issue by Romiko** [Azure/terraform-azurerm-lz-vending#362]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

We use Rover and the CAF Super Module to provision Level0, Level 1, level 2 resources.

- [Super Module](https://github.com/aztfmod/terraform-azurerm-caf)
- [Azure Terraform SRE -  formely CAF Terraform](https://github.com/Azure/caf-terraform-landingzones)

We find the Level3 Subscription vending in the CAF Super Module to be very limited regarding the vending of workload subscriptions at level3. We do not want multple stages to apply terraform.

e.g. We want to use rover to provision Level 3 vending subscriptions. Rover -target_subscription. makes no sense to use when vending a subscription.- [Rover Commands](https://aztfmod.github.io/documentation/docs/rover/rover-commands)

### Describe the solution you'd like
The  [Azure Terraform SRE -  formely CAF Terraform](https://github.com/Azure/caf-terraform-landingzones/tree/main/caf_solution/add-ons). has an add-ons feature.

We already use the caf_eslz module and aci_azure_devops_agent, so it would be awesome to have this repo here as an **Add-On** for better Subscription vending for Level3 in [this location](https://github.com/Azure/caf-terraform-landingzones/tree/main/caf_solution/add-ons)

Use the CAF super module and Azure Terraform SRE Add-Ons to provision subscriptions using this repo. This would allow references to previous Terraform statefiles from level0, level1, level2.

Alternatively, any suggestions on how we can deploy resources using this repo but also reference previous level state files e.g.
[Code-less composition across state files](https://aztfmod.github.io/documentation/docs/fundamentals/lz-composition)

`automations = {
  account1 = {
    name = "automationAccount1"
    sku  = "Basic"
    resource_group = {
      key    = "auto-account"
      lz_key = "launchpad"
    }
  }
}`

lz_key is critical to reference previous terraform provisioning from level0, level1 and level

### Additional context
Open to suggestions to have this as an add-on in [Azure Terraform SRE -  formerly CAF Terraform](https://github.com/Azure/caf-terraform-landingzones/tree/main/caf_solution/add-ons)

Or how else can we integrate it and also with rover e.g. Wishlist below

`rover -lz /tf/caf/landingzones/caf_solution/add-ons/terraform-azurerm-lz-vending/ \
  -level level3 -tfstate level3_azure_subscriptions.tfstate \
  --tfstate_subscription_id 000000000-0000-0000-0000-000000000000 \
  -var-folder /tf/caf/configuration/level3/subscriptions \
  -parallelism 30 
  -env Production \
  -a plan`
  
  It makes no sense to have target_subscription (Rover will default to az cli default), regardless of whether tfstate subscription is required. The reason is that if you are providing a subscription, you would not know the target subscription ID!

Thoughts? I also see the CAF SuperModule has no longer MS support! We are already heavily invested in CAF Supermodule. Microsoft are now saying to use https://azure.github.io/Azure-Verified-Modules/concepts/what-why-how/. However, how does Rover and our existing efforts get migrated across? Whilst maintaining Code-less composition across state files across all levels (0 - 4).

Lastly non of the CAF / Landing Zone modules are in the AZM catalog as of todays date:
https://azure.github.io/Azure-Verified-Modules/indexes/terraform/tf-resource-modules/

So what should we do when choosing a framework with long-term support when we are already heavily using CAF Super Module and Azure Terraform SRE?

I see there are PATTERN Modules here now:
https://azure.github.io/Azure-Verified-Modules/indexes/terraform/tf-pattern-modules/

- [avm-ptn-alz](https://registry.terraform.io/modules/Azure/avm-ptn-alz/azurerm/latest)
- [avm-ptn-alz-management](https://registry.terraform.io/modules/Azure/avm-ptn-alz-management/azurerm/latest)
- [avm-ptn-virtualwan](https://registry.terraform.io/modules/Azure/avm-ptn-virtualwan/azurerm/latest)
- [avm-ptn-vnetgateway](https://registry.terraform.io/modules/Azure/avm-ptn-vnetgateway/azurerm/latest)

@matt-FFFFFF Are you able to provide some advice here?

**Comment by matt-FFFFFF** [comment]
The Azure Terraform SRE project is a community effort and questions regarding integration between this module and it should be directed there.

We do not have a working knowledge of the SRE system so cannot comment unfortunately.

**Comment by matt-FFFFFF** [comment]
The direction of the Azure Landing Zones team is to leverage AVM for all future modules. You have already picked out some of the key offering here.

**Comment by Romiko** [comment]
Thanks Matt. I will keep a close eye on the AVM and see how I can assist. When is a good time to migrate off the super module?
