### ISSUE TITLE
bug: incorrect validation on subscription display name

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-lz-vending#373]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

```text
Terraform v1.8.2
```

Please enter the module version that you are using:

```text
4.1.0
```

### Description

subscription display name validation fails for subscription with valid names.  e.g. you can have brackets in a subscription display name

hashicorp's validation is much less strict

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/subscription/validate/subscription_name.go

```golang
	if len(v) > 64 || v == "" {
		errors = append(errors, fmt.Errorf("Subscription Name must be between 1 and 64 characters in length"))
	}

	if regexp.MustCompile("[<>;|]").MatchString(v) {
		errors = append(errors, fmt.Errorf("Subsciption Name cannot contain the characters `<`, `>`, `;`, or `|`"))
	}
```	

I struggle to find the source of truth in the API specs, perhaps i'm looking in the wrong place, I tried looking here - https://github.com/Azure/azure-rest-api-specs

**Comment by zebak007** [comment]
This fix has broken my alz vending process in my lab....

subscription_display_name is optional if you use ALZ vending with existing subscription (aka you don't create subscription). 

Description: Whether to create a new subscription using the subscription alias resource.

**If enabled,** the following must also be supplied:

subscription_alias_name
subscription_display_name
subscription_billing_scope
subscription_workload

After upgrade to 4.1.3 I am getting this error 

│ Error: Invalid value for variable
│
│   on .terraform\modules\lz_vending\main.subscription.tf line 11, in module "subscription":
│   11:   subscription_display_name                            = var.subscription_display_name
│     ├────────────────
│     │ var.subscription_display_name is ""
│
│ Subscription Name must be between 1 and 64 characters in length and cannot contain the characters `<`, `>`, `;`, or `|`
│
│ This was checked by the validation rule at .terraform\modules\lz_vending\modules\subscription\variables.tf:58,3-13.
╵
