### ISSUE TITLE
bug: AzAPI Provider - Resource group - Azure Policy Mandatory Tags 

### ISSUE THREAD

**Issue by Romiko** [Azure/terraform-azurerm-lz-vending#379]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
Terraform v1.5.6
```

Please enter the module version that you are using:

```text
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.0"
    }

    azuread = {
      source  = "hashicorp/azuread"
      version = "~>2.0"
    }
  }
}
```

### Description
If you have an azure policy with mandatory tags for resource group. The terraform fails even if you have defined all mandatory tags when you provision a VNET for that resource group.

#### Steps to Reproduce

1. Create an Azure Policy with mandatory tags and apply it to a subscription
2. Create a resource group using AzApi
3. Succeeds

1. Create an Azure Policy with mandatory tags and apply it to a subscription
2. Create a resource group and a VNET (without specifying resource_group_tags)
3. fails

VNET should not try to overwrite the resource group tags if resource_group_tags is not set in the vnet and the resource group was created outside of the vnet.

#### Additional context

##[error]Bash wrote one or more lines to the standard error stream.
##[error]2024-05-09T23:11:30.191Z [ERROR] provider.terraform-provider-azapi_v1.13.1: Response contains error diagnostic: tf_provider_addr=registry.terraform.io/Azure/azapi tf_resource_type=azapi_resource @caller=github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov6/internal/diag/diagnostics.go:58 diagnostic_detail="creating/updating Resource: (ResourceId "/subscriptions/xyz/resourceGroups/rg-xyz-test-001" / Api Version "2021-04-01"): PUT https://management.azure.com/subscriptions/XYZ/resourceGroups/rg-xyz-test-001
--------------------------------------------------------------------------------
RESPONSE 403: 403 Forbidden
ERROR CODE: RequestDisallowedByPolicy

**Comment by matt-FFFFFF** [comment]
Hi. Looking at your steps above, this is the expected behaviour of azure policy.

You would have to supply all required tags in the AzAPI resource in order to be compliant.
