### ISSUE TITLE
feat: Allow Azure API accepted chars in subscription_tags

### ISSUE THREAD

**Issue by Solaflex** [Azure/terraform-azurerm-lz-vending#383]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

**Is your feature request related to an issue?**
In #332 , there is the claim that `<>%&\?/.` are illegal chars by Azure and are therefore not accepted as tag names. However, we have not observed this in reality. We use one Tag Value to keep track of specific internal domains. The URL obviously contains at least `/`, sometimes also `?` and rarely `%` for encoding. 

### Describe the solution you'd like

Please reconsider the validation RexEx in this line to allow chars which are accepted by Azure. It is unclear for me how the original author came to the conclusion that these chars are illegal in #332 

https://github.com/Azure/terraform-azurerm-lz-vending/blob/192949e49199c1cc3e6c1d866bf47869a860dc89/modules/subscription/variables.tf#L156-L169

**Comment by luke-taylor** [comment]
Hey, actually the code for this has already been merged into main, I have just cut the release for v4.1.1 which should include the change. Thanks,

Luke
