### ISSUE TITLE
Terraform can not read role assignment created along subscription using module

### ISSUE THREAD

**Issue by ShadiAlbatal** [Azure/terraform-azurerm-lz-vending#392]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

terraform {
  required_version = ">= 1.5.5"

  backend "azurerm" {
    use_azuread_auth = true
  }

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.74.0"
    }
  }
}

Please paste the output of `terraform version` command from within the initialized directory:

```text
- Using previously-installed hashicorp/random v3.6.2
- Using previously-installed azure/azapi v1.13.1
- Using previously-installed hashicorp/azuread v2.51.0
- Using previously-installed hashicorp/azurerm v3.107.0
- Using previously-installed hashicorp/time v0.11.2
```

Please enter the module version that you are using:

```text
  source                                            = "Azure/lz-vending/azurerm"
  version                                           = "3.4.1"
```

#### Steps to Reproduce

create subscription and create role assignment for it, the role assignment is created.
tf
![Namnlös](https://github.com/Azure/terraform-azurerm-lz-vending/assets/23479946/79d1e910-8918-48be-ad61-4470f64c1263)
plan
![image (2)](https://github.com/Azure/terraform-azurerm-lz-vending/assets/23479946/8f8a2deb-e895-4cd4-ba88-0980c266d84f)
apply
│ Error: loading Role Assignment "/subscriptions/xxxxx-xxxx-xxxx-xxxx-xxxxx/providers/Microsoft.Management/managementGroups/st-sandboxes/providers/Microsoft.Authorization/roleAssignments/xxxxx-xxxx-xxxx-xxxx-xxxxx": authorization.RoleAssignmentsClient#GetByID: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2020-04-01-preview' is invalid. The supported versions are '2024-03-01,2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."

#### Additional context

not sure if related but running from local shell give (I have owner permission)
│ Error: reading Subscription Alias "it-sandbox": subscriptions.SubscriptionsClient#AliasGet: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="UserNotAuthorized" Message="User does not have access Microsoft.Subscription/aliases/write over scope providers/Microsoft.Subscription/aliases/it-sandbox"
│
│   with module.sandbox_subscriptions["itsbx"].module.subscription[0].azurerm_subscription.this[0],
│   on .terraform\modules\sandbox_subscriptions\modules\subscription\main.tf line 2, in resource "azurerm_subscription" "this":
│    2: resource "azurerm_subscription" "this" {

**Comment by matt-FFFFFF** [comment]
Hi,

Please can you tell me the relative scope you supplied to the role assignment?

**Comment by matt-FFFFFF** [comment]
Reason I ask is that all role assignments are relative to the subscription scope.

It seems like you want to create a role assignment at management group scope. If you want to do this you will have to do it outside the module.

See docs here:

https://github.com/Azure/terraform-azurerm-lz-vending?tab=readme-ov-file#input_role_assignments

**Comment by ShadiAlbatal** [comment]
Yes, i was trying to do so. How do you mean doing it outside the module? should i create a separate role assignment för that?

**Comment by ShadiAlbatal** [comment]
Any idea about the second error message?

**Comment by matt-FFFFFF** [comment]
> Yes, i was trying to do so. How do you mean doing it outside the module? should i create a separate role assignment för that?

Yes, create the role assignment in your main.tf, or similar.

**Comment by matt-FFFFFF** [comment]
> Any idea about the second error message?

I suspect that the error will go away once you fix the role assignment issue

**Comment by ShadiAlbatal** [comment]
I removed the role assignment from state file since it could not find it was created in portal, so that issue has gone, but by mistake the subscription was deleted from state file, so if i try to import it back or if i run plan from my local, the same error will keep showing up (the error about subscription alias )

**Comment by matt-FFFFFF** [comment]
I would recommend the at you never remove anything from the state file.

Terraform now has import and removed blocks to achieve the same.

Importing the alias resource is difficult. I would recommend configuring the module with the existing subscription id and managing the sub as if it was not created by this module.
