### ISSUE TITLE
bug: Azure Pipelines AZAPI execution fails with "ChainedTokenCredential authentication failed"

### ISSUE THREAD

**Issue by jarhorn** [Azure/terraform-azurerm-lz-vending#401]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
Terraform v1.7.1
on windows_amd64
+ provider registry.terraform.io/azure/azapi v1.12.1
+ provider registry.terraform.io/hashicorp/azuread v2.48.0
+ provider registry.terraform.io/hashicorp/azurerm v3.99.0
+ provider registry.terraform.io/hashicorp/time v0.11.1
```

Please enter the module version that you are using:

```text
4.1.2
```

### Description

We are currently running into trouble using a SPN with Azure Pipelines and any calls made with the azapi provider.  Using AzureAD, AzureRM, etc. providers works without issue.

Successfully created:
- Azure AD Group
- AzureRM Subscription
- AzureRM Management Group Subscription Association
- AzureRM Role Assignment

Failed to create:
- Telemetry
- Budgets

#### Steps to Reproduce

1. Run `az login` using Service Principal (Azure Pipelines)
2. Verify login by changing subscription `az account set`
3. Initialize Terraform (`terraform init`)
4. Create Terraform Plan (`terraform plan`)
5. Attempt to execute Terraform with `terraform apply`

#### Screenshots

The errors look like this:

![image](https://github.com/user-attachments/assets/b2f7f5df-0218-478d-a440-f85d9045e4f1)

(I have attached the raw log)
[AzPipeline-RawLog-AzSubscriptionAzApiFail.txt](https://github.com/user-attachments/files/16362676/AzPipeline-RawLog-AzSubscriptionAzApiFail.txt)

#### Additional context

We are able to perform this activity without issue running this outside the pipeline.

Feels like there is an environment variable/setup we are missing for our Azure Hosted pipeline agents.

**Comment by jchryst-pack** [comment]
Seeing the same behavior. Can run the plan no issues locally with aliased providers. When running in a pipeline get the same error.

**Comment by matt-FFFFFF** [comment]
Hi this isn't a module bug and should be reported on the AzAPI provider repo.

However you to fix you have to explicitly disable MSI authentication in the provider config.
