### ISSUE TITLE
bug: UMI changing output properties forcing RBAC replacment each time running terraform plan/apply

### ISSUE THREAD

**Issue by chrsundermann** [Azure/terraform-azurerm-lz-vending#415]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
terraform 1.9.5
azurerm 3.99.0
azapi 1.14.0
time 0.11.2
```

Please enter the module version that you are using:

```text
Used 2 versions of the module, same behaviour:
Versions: 4.1.2 & 4.1.3
```

### Description

Creating UMI with following configuration calling the module:
![image](https://github.com/user-attachments/assets/f488267c-73dd-4481-bc2f-5f6080735b88)

Both resource groups will be created by the module as well and locks disabled after problems assigning permissions to them.

This is my output each time my pipeline is running (expected "no changes"). I get the same when I run it on my container with terraform version 1.9.1 & azapi 1.14.0 & azurerm 3.99.0 & time 0.11.2

![image](https://github.com/user-attachments/assets/0538da42-f820-431b-8fb1-b9c81e7fc19e)

#### Steps to Reproduce

Create UMI with the above configuration and it should be the same behaviour.

**Comment by matt-FFFFFF** [comment]
Hi,

I see the tags are getting reset on the UMI, potentially causing this issue.

Are you using azure policy to inherit tags at all?

**Comment by chrsundermann** [comment]
Sorry for late response, I was on holidays.

Looking into the tagging policy thing. Inheritance of tags aren't set via Cost Management but I will look into the policies itself. Get back as soon as possible with details.

**Comment by chrsundermann** [comment]
@matt-FFFFFF Yes, your right. Policy Inheritance was set on top level and setting the 'umi_tags" variable to exact key/value pair fixed the repeating reprovisioning. Result now, 'no changes'.
