### ISSUE TITLE
bug: New attempts to create subscription fail on 'terraform validate' due to invalid body being passed

### ISSUE THREAD

**Issue by juddlestone** [Azure/terraform-azurerm-lz-vending#426]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

```text
1.9.5
```

Please enter the module version that you are using:

```text
4.1.2
```

#### Steps to Reproduce

1. Create subscription utilizing module
2. Make a change to said existing subscription, in this case the the decreasing the budget from 5000 to 200. 
3. Run 'terraform validate', which then fails. 

#### Screenshots

Screenshot 1:
![Image](https://github.com/user-attachments/assets/6e37e8aa-9c3f-42b1-bc31-cc196e96410e)

Screenshot 2:
![Image](https://github.com/user-attachments/assets/7110b93e-ed04-487a-a860-1fed694d5798)

Screenshot 3:
![Image](https://github.com/user-attachments/assets/8b529bf4-85c2-452f-9fe5-e736f4c25c23)

#### Additional context

Since implementing subscription vending, we have created a number of subscriptions end to end successfully. Last Thursday (17/10/2024) a request for an additional sandbox subscription was submitted and created for our end users. Today, 23/10/2024 a request was made to amend this subscriptions budget which was incorrectly submitted. 

Previously this value was 5000, and was changed to 200. Upon pushing this change, our expected triggers and following automation ran. However, it now fails on the 'terraform validate' step. The change was reverted to the previous value, but we continue to see this behaviour now.

**Comment by matt-FFFFFF** [comment]
Hi, this is because AzAPI v2 is out and we don't yet support it.

You can pin your provider version whilst we release a patch to correct.

**Comment by matt-FFFFFF** [comment]
See #406
