### ISSUE TITLE
feat: upgrade azapi provider

### ISSUE THREAD

**Issue by SamSh-585** [Azure/terraform-azurerm-lz-vending#431]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

Many modules inside the lz-vending use an old version of Azapi. Due to provider version conflicts, using the lz-vending module with other self-created Azapi resources with the latest version is impossible. Workarounds can be done by separating the lz-vending and the self-created resources in different root modules, but this is not always ideal.

### Describe the solution you'd like
Upgrade azapi in the required providers for the underlying resources to the newest azapi version (as it doesn't require much effort).

**Comment by matt-FFFFFF** [comment]
Hi!

Thanks for raising this, we have this on our backlog and are tracking at #406

Closing this in favour of the original issue
