### ISSUE TITLE
feat: Does this module support multi-tenant MCA-E billing configuration

### ISSUE THREAD

**Issue by MarcelHeek** [Azure/terraform-azurerm-lz-vending#432]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

I know that the module is capable of vending subscriptions for a MCA contract where the MCA license is local to the tenant. The setup we are facing is that there is one MCA Billing Account defined in the "main/source" tenant, and we have several "destination" tenants that are part of this contract by way of invoice sections.

In the documentation for [programatically creation of subscriptions across tenants in MCA scenario](https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-microsoft-customer-agreement-across-tenants) we learn that the subscription is to initially be provisioned in the source tenant and then be transferred (change ownership) to the destination tenant. In the API call to facilitate that I can see the following additional properties that need to be provided in the call

```
PUT https://management.azure.com/providers/Microsoft.Subscription/aliases/{{guid}}?api-version=2021-10-01
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "properties": {
    "displayName": "{{subscription_name}}",
    "workload": "Production",
    "billingScope": "/billingAccounts/{{billing_account}}/billingProfiles/{{billing_profile}}/invoiceSections/{{invoice_section}}",
    "subscriptionId": null,
    "additionalProperties": {
      "managementGroupId": null,
      "subscriptionTenantId": "{{destination_tenant_id}}",
      "subscriptionOwnerId": "{{destination_service_principal_id}}"
    }
  }
}
```

I can see that the module does not support these additional properties (yet). On top of that the destination tenant principal with the right billing permissions needs to accept the ownership transfer using an API call, which in Terraform logic 

We still would like to keep using this module but I fear we have to abandon it now for lack of the multi-tenant MCA configuration we are forcefully moved into as our procurement office without having a clue of the effects changed the contract from EA to MCA-E. Leaving us crippled as this broke our multi-tenant vending solution using this module.

Do you have any pointers for us on what we could do? Is MCA multi-tenant somewhere on the road map, so we could revert back to this module at some point? 

Any comments / suggestions are appreciated

### Describe the solution you'd like

I would like to see the multi-tenant MCA billing setup available in the module

**Comment by jtracey93** [comment]
Hey @MarcelHeek,

This doc from the PG is a way to do it, but not the way ive done it with customers. after working with the MCA PG to discover a better way and more like the way it works on an EA.
 
They way to do it is as per below:

1. Create associated tenant link from primary tenant
2. In primary tenant invite user from associated tenant with billing owner (so they can grant RBAC to SPN later) on desired scope
3. User doesn't have to have a mailbox - use invite link instead via manage requests on billing profile/scope
4. Accept iniviation as invitied user in their home tenant
5. As newly invited user, grant single tenant SPN/App sub creator on desired billing profile/scope
6. Create subs as SPN/App etc. 

[Manage billing across multiple tenants - Microsoft Cost Management | Microsoft Learn](https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/manage-billing-across-tenants)

Let me know if this helps, as you can use this module then and just run the module with an identity with the SPN from each tenant and the sub will appear in each tenant as desired 👍

**Comment by MarcelHeek** [comment]
@jtracey93 

Thanks....You saved the day. This works like a charm. The PG should update their documentation to provide this alternative method.
