### ISSUE TITLE
Default example missing Virtual_network_name

### ISSUE THREAD

**Issue by danielmarker** [Azure/terraform-azurerm-lz-vending#76]
On the root of the Readme, the example given, when ran, requires "virtual_network_name" - running without this variable caused an error.

**Comment by danielmarker** [comment]
![image](https://user-images.githubusercontent.com/8668101/182810823-569dd5e3-93df-4985-828c-e0867d7344a7.png)
image above

**Comment by matt-FFFFFF** [comment]
Thanks - good catch, wil fix!
