### ISSUE TITLE
Clarify value of `subscription_billing_scope`

### ISSUE THREAD

**Issue by frankscalzo** [Azure/terraform-azurerm-lz-vending#90]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.2.7

**azure provider**:  3.7

**module**: subscrtion

#### Describe the bug

im trying to see if i am doing something wrong 

i do not want to have the modules int he .terraform so i am using raw files 

added a providers .tf with feature block as needed 

added the variables that i could find int he variables.subscription.tf

wanted to make sure 1
the 

/providers/Microsoft.Billing/billingAccounts/ ( IS THE SUBSCRITION ID) 

and 2

after entering the required items from the comments i still get these errors?

i dont see where i am suppose to enter these.

╷
│ Error: ID was missing the `billingProfiles` element
│ 
│   with module.subscription[0].azurerm_subscription.this[0],
│   on modules/subscription/main.tf line 6, in resource "azurerm_subscription" "this":
│    6:   billing_scope_id  = var.subscription_billing_scope
│ 
╵
╷
│ Error: ID was missing the `enrollmentAccounts` element
│ 
│   with module.subscription[0].azurerm_subscription.this[0],
│   on modules/subscription/main.tf line 6, in resource "azurerm_subscription" "this":
│    6:   billing_scope_id  = var.subscription_billing_scope
│ 
╵
╷
│ Error: ID was missing the `customers` element
│ 
│   with module.subscription[0].azurerm_subscription.this[0],
│   on modules/subscription/main.tf line 6, in resource "azurerm_subscription" "this":
│    6:   billing_scope_id  = var.subscription_billing_scope
│  

#### Steps to Reproduce

1. step 1
2. step 2
3. you get it...

**Comment by matt-FFFFFF** [comment]
Hi @frankscalzo 

The billing scope value is used when creating new subscriptions programatically and should be set as per this:

https://docs.microsoft.com/en-us/azure/templates/microsoft.subscription/aliases?pivots=deployment-language-bicep#putaliasrequestpropertiesorsubscriptionaliasresponseproperties

I will update the documentation for this variable accordingly https://github.com/Azure/terraform-azurerm-lz-vending#input_subscription_billing_scope

You need access to an EA, MPA or MCA.

However you can also use this module with existing subscriptions: https://github.com/Azure/terraform-azurerm-lz-vending/wiki/Example-5--Use-with-existing-subscriptions

**Comment by frankscalzo** [comment]
i was able to solve the issue i found when using the cli to get the ID is that it came back with null and was incomplete.

i was only getting the 

/providers/Microsoft.Billing/billingAccounts/12345

and not 

/providers/Microsoft.Billing/billingAccounts/12345/enrollmentAccounts/DB4C-XXXX

i had to manually look the rest of the scope info up on the UI to get the id of the scope 

i have made it past this issue and on to a new one regarding alias creation

ill push through but any insight is appreciated 

module.subscription[0].azurerm_subscription.this[0]: Creating...
╷
│ Error: creating new Subscription (Alias "epiprod"): subscription.AliasClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Specified method is not supported."

**Comment by frankscalzo** [comment]
@matt-FFFFFF  sorry i was able to solve i was reading a differnt post than you sent and it talked about enrollment account 

which had got me past the error 

it was not until i dug deeper and saw that with MSC you need to do 

/billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/invoiceSections/{invoiceSectionName}

thanks again ill keep running through

**Comment by matt-FFFFFF** [comment]
Glad I was able to help! Come back if you get stuck again.
