### ISSUE TITLE
Feature Request using this for initial subscriptions for CAF enterprise deployments

### ISSUE THREAD

**Issue by frankscalzo** [Azure/terraform-azurerm-lz-vending#94]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

**Is your feature request related to an issue?**

### Describe the solution you'd like

SO i am wondering if you can use this vending as a pre cursor in the CAF enterprise deployment to create the first 3 needed subscriptions  by modifying the var values and using the outputs from their creation to fill in the providers.tf variables for the subscription IDs

**Comment by matt-FFFFFF** [comment]
Hi there @frankscalzo 

It is possible to use this module to create the subscriptions for the [ALZ Terraform module](https://aka.ms/alz/tf), but this will not be idempotent. You will have to use the first `terraform apply` to create the subscriptions, then use the newly created subscription IDs in the provider declarations of the ALZ Terraform module for a second apply.

This is a well-known constraint of the AzureRM provider, in that it must be linked to a specific subscription at the time that `terraform init` is run. Given that we do not know the ID of the to-be created subscriptions at the time of the init process, this creates a circular dependency.

We recommend using other means to create the three initial subscriptions required for ALZ Terraform module, then using this module to create the application landing zone subscriptions.

/cc @krowlandson
