### ISSUE TITLE
Feature Request: Allow for more than one vnet per subscription

### ISSUE THREAD

**Issue by ChrisTav424** [Azure/terraform-azurerm-lz-vending#97]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

**Is your feature request related to an issue?**

No open issue but we cannot use the module to build more than one vnet per subscription

### Describe the solution you'd like

We would like the ability to add more than one vnet per subscription. The use case for this is when you have one subscription but using resources in multiple regions. For example:

Subscription: "AVD"
Vnet1: "vnet-avd-uksouth"
Vnet2: "vnet-avd-ukwest"

At present the yaml /module only supports one vnet (example)

```
display_name: avd
name: avd
workload: Production
location: uksouth
management_group_id: lz-avd
vnet_rg_name: rg-vnet-avd
vnet_name: vnet-avd-uksouth
vnet_address_space:
  - "10.0.3.0/24"
  - "192.168.3.0/24"
```

It looks like vnets could use a terraform map the same way that role assigments does. 

As a workaround we will be trying to use the [Example 5 Use with existing subscriptions ](https://github.com/Azure/terraform-azurerm-lz-vending/wiki/Example-5-Use-with-existing-subscriptions ) to add more vnets or native terraform. 

### Additional context
Module is brilliant, keep up the good work :)

**Comment by matt-FFFFFF** [comment]
As a workaround, you can instantiate the module more than once. On the second instance, specify the subscription ID of the created subscription and then add another vnet.

**Comment by ChrisTav424** [comment]
Thanks @matt-FFFFFF I hadn't considered the implications on vnet peering etc. 

We've done exactly that as workaround, as we know we want exactly two vnets per subscription (one for uks and one for ukw) we have used [Example-5-Use-with-existing-subscriptions](https://github.com/Azure/terraform-azurerm-lz-vending/wiki/Example-5-Use-with-existing-subscriptions) uks and ukw network 

**main.tf**
```
module "lz_second_vnet" {
  source   = "Azure/lz-vending/azurerm"
  version  = "1.0.1"
  for_each = local.landing_zone_data_map
  location = each.value.default_location

  # subscription variables
  subscription_id = module.lz_vending[each.key].subscription_id

  # virtual network variables
  virtual_network_enabled             = true
  virtual_network_location            = "ukwest"
  virtual_network_address_space       = each.value.vnet_ukw_address_space
  virtual_network_name                = each.value.vnet_ukw_name
  virtual_network_resource_group_name = each.value.vnet_ukw_rg_name
  disable_telemetry                   = true
}
```

**landing_zone_example.yaml**
```
---
display_name: azure prod connectivity
name: azure-prod-connectivity
workload: Production
default_location: uksouth
management_group_id: hmlr-connectivity
vnet_uks_rg_name: rg-vnet-prod-uksouth-connectivity
vnet_uks_name: vnet-prod-uksouth-connectivity
vnet_uks_address_space:
  - "10.0.1.0/24"
vnet_ukw_rg_name: rg-vnet-prod-ukwest-connectivity
vnet_ukw_name: vnet-prod-ukwest-connectivity
vnet_ukw_address_space:
  - "10.0.2.0/24"
role_assignments:
  - principal_id: <removed>
    definition: Owner
    relative_scope: ''
  - principal_id: <removed>
    definition: Reader
    relative_scope: ''

**Comment by matt-FFFFFF** [comment]
Started work on this in the linked branch
