### ISSUE TITLE
Feature Request: Support for resource group and vnet tags

### ISSUE THREAD

**Issue by ChrisTav424** [Azure/terraform-azurerm-lz-vending#99]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

**Is your feature request related to an issue?**

We have a policy which enforces tags, at present this module doesn't support tags on resource groups or vnets. 

### Describe the solution you'd like

Add support for tags on resource groups and vnets. 

 We have a policy which enforces tags which means we have to delete the assignment / add an exception to allow resource group or vnets to be built. 

### Additional context
I did see that #62 added support to use tags with subscriptions.

**Comment by owejak** [comment]
I've had a similar issue as well

**Comment by f0cusN0w** [comment]
Ditto here as well. We are successful in creating tags for subscriptions but not for the underlying resources ;-(

Regards

**Comment by matt-FFFFFF** [comment]
Hi, thanks for your request. We will look at this in v2.0.0 with Terraform 1.3, for the same reasons as discussed in #97

**Comment by ChrisTav424** [comment]
Thanks @matt-FFFFFF

In the meantime we will disable the policy unless there's a better workaround?

**Comment by matt-FFFFFF** [comment]
Hi,

Have you considered inheriting tags from the subscription/resource group instead?

I'd be interested to understand what tags you seem are 'required'.

Thanks!

**Comment by matt-FFFFFF** [comment]
Terraform 1.3 is now at rc1 build. Won't be long now:

https://github.com/hashicorp/terraform/releases/tag/v1.3.0-rc1

**Comment by ChrisTav424** [comment]
Thnks @matt-FFFFFF . To answer your question about tags, we are using terms like "owner", "description", "on-call". Probably overkill for resource groups and vnets but creates consistancy and makes the policy easier to implement.

**Comment by matt-FFFFFF** [comment]
Thanks!
